### ISSUE TITLE
App 2.1: change of certificat settings is not taken into account as expected

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#857] opened 2018-04-23 09:07 UTC
After changing a certificate setting, the connection is done without this changed setting. Even pushing the Retry button does not help. You have to close/unload the app using Android feature. Then when you restart the app, the new settings are considered.

**Comment by maniac103** [comment] 2018-04-23 12:44
Dupe of #810?

**Comment by lolodomo** [comment] 2018-04-23 12:48
Yes looks similar.

**Closed** 2018-04-23 14:55 UTC
Labels: duplicate
