### ISSUE TITLE
possibility of show text with values in  "one line" 

### ISSUE THREAD

**Issue by mkrathome** [openhab/openhab-android#3173] opened 2023-01-30 17:15 UTC
Hello again, 

After 3 Days with the new Design, I agree with you, that it is a pretty nice style (in the meantime I love that flat and clear look) also I understood the need of the 2-line dessicion. 
I read many times here and also at the openhab-community, that you are possibly think about a way to have the opportunity to show text with a value-item in one line.
To prevent of misunderstood:

I don't ask for a change of the complete design  and also not for a general switch for all types of widgets.
But I think it is worth to think about a possibility for text  which has additional item+value. 

Please understand this as an politely whish from my side🖖🏻

All the best 

Manuel

**Comment by mueller-ma** [comment] 2023-01-30 21:15
Hi,

thanks for your feedback 👍 

There are two related changes that people don't like:
1. Label and values are in 2 lines.
2. There's more padding than before.


*If* I will add a second layout for text widgets, it should "fix" both changes. However that would have two disadvantages:
1. Some values will be in the first line (in text widgets) , for some other values it will be in the second line, e.g. selection.
2. The line height of text widgets will be different to the height of all other widgets.

To compensate these two issues we would need to duplicate the views for all widgets, which makes the app harder to maintain.
In the other issue (#3159) there's a lot of discussion about "customer requirements". Here's mine: The app must be easy to maintain. Otherwise @maniac103 and I cannot maintain it in our limited free time and development would stop.

What's your opinion about this? Would you prefer the text value in one line and accept inconsistent line heights and value positions?

Best wishes,
@mueller-ma

**Comment by mkrathome** [comment] 2023-01-31 06:58
Hi,

Thank you for the un-emotional feedback, 

Because of the not usefully and sometimes ugly discussion in issue #3159 I opened this one.

I understood, the advantages of easy maintaining the app (because we are all glad, that you and maniac are spend a lot of your private time to develop and keep it running).

For me personally it would be ok, if only text widgets has the possibility to "break" the design, because than it's my own dessicion (and work in the Page-Definition) to compensate that.

Most of my sitemap pages are very nice with the new flat-design and I like even the highlighting of the frame-names 🙈.... But this is another story.....

But there are also "pages" with only Text-Widgets from the same or similar type for a fast check. 

So in the End for me it is not a question of to bee ore not to bee maybe only a whish, which I hope it could be realized by some fancy "Programmers-trick"  like some controlling-signs in the Metadata or so...

You see I'm not so familiar with the things behind because more sitting in front of your work🙈

So please keep on running as long you have at least a little bit fun in doing this great job 👍🏻

All the best 

Manuel

**Comment by kaikreuzer** [comment] 2023-01-31 17:23
I very much support @mkrathome wish here - I also have many pages with mainly text widgets that show different kinds of measurement values. Having these values presented "table-like", i.e. labels left and values right is (a) much easier to read and (b) more efficient with space, so that more fits onto the screen. 

Reducing the padding, so that the same label length fits onto the screen (as with the previous) version, would also help and would be beneficial for keeping a better backward compatibility (otherwise, every user is forced to revise their sitemaps and change the texts to shorter strings, which should imho be avoided).

If the compromise is that widgets with controls have a different height, so be it. From what I see in MD, this is something rather usual and nothing to be avoided, right?

**Comment by maniac103** [comment] 2023-01-31 18:24
> Reducing the padding, so that the same label length fits onto the screen (as with the previous) version, would also help

While 'Material Design' is a term that's interpreted relatively freely among apps and their developers, the design spec actually is pretty strict/concrete when it comes to padding in list elements - see [here](https://m3.material.io/components/lists/specs#129ef830-d120-45fe-94b4-a6b4346a87b4). Thus one of the things I definitely do *not* want to change with the new layout (unless we revert it completely, which is obviously something I do *not* want either) is changing the paddings.
Since the font sizes are smaller now than before, there should be no space issues due to the paddings either. Additionally, since screen sizes differ, spacing between different devices will always be a compromise.

> If the compromise is that widgets with controls have a different height, so be it. From what I see in MD, this is something rather usual and nothing to be avoided, right?

Yes, but the problem is that everybody has somewhat different objectives and use cases. There are people who want to cram as much as possible into one 'page', some who just want right aligned values and don't really care about space otherwise, some even want multi line values (#576, #676). If we want to support everything, that would mean needing more than one option and more than 2 layouts for every widget, which would be a maintenance nightmare.
The idea we're currently pondering is one option to toggle between 'new' and 'old-ish' layout, where the latter means 'layout similar to before, just with new font sizes and padding'.

**Comment by mkrathome** [comment] 2023-01-31 19:04
> The idea we're currently pondering is one option to toggle between 'new' and 'old-ish' layout, where the latter means 'layout similar to before, just with new font sizes and padding'.

Thank you for pondering (I had to "Google" that🙈)
For me (and I think the most of the other users which are not so lucky with all the changes) this sounds great. Means I will have the flat-design along with the 'old-ish' layout? But the slider instead of the number-picker?

Take as much time as you need to think and fetch some ideas....
and in the end every user has to make compromises because otherwise he/she/it would be a developer too😉 and create his very own app...

This is one point, I decided to choose openHAB, it ist unbelievable flexible... also if I use not everything in the way the developers designed it for🙈

Best Wishes and again thanks for all your time 

Manuel

**Comment by kaikreuzer** [comment] 2023-01-31 22:53
> one of the things I definitely do not want to change [...] is changing the paddings.

Ah, sorry, I understood @mueller-ma  above that this is something that you (or just him?) WOULD address at the same time as showing values on the right ("If I will add a second layout for text widgets, it should "fix" both changes").

> Since the font sizes are smaller now than before

In comparison to Google's own apps (e.g. "Home"), the font imho looks a bit too small now (and the toggles too huge in comparison to the font size):

<img width="477" alt="Bildschirm­foto 2023-01-31 um 23 28 03" src="https://user-images.githubusercontent.com/3244965/215898061-0bcff0e8-e91b-4aaf-a18b-8de4047e3844.png">

> there should be no space issues due to the paddings either.

But there is, that's what I meant with "broken backwards compatibility". See e.g. these examples:

<img width="739" alt="Bildschirm­foto 2023-01-31 um 23 44 31" src="https://user-images.githubusercontent.com/3244965/215900790-ce570fd5-0ec7-4ff6-9fc6-9d902a8b8057.png">

<img width="738" alt="Bildschirm­foto 2023-01-31 um 23 46 40" src="https://user-images.githubusercontent.com/3244965/215901157-e3086eb4-0516-4063-bc5c-3b0917c7b6b9.png">

> the problem is that everybody has somewhat different objectives and use cases.

Agreed, but I actually thought that for providing a huge flexibility, the feature to use the Main UI within the app had been added. As this gives huge freedom for everyone for custom layouts, I would think that the "classic" UX of openHAB, which exists since 12 years should only be carefully changed - and at least my impression is that long-term users really love the "cramped" design that makes efficient use of small screens. This is actually something where I considered the openHAB apps always superior to any app from a "smart" manufacturer, because it is able to deal with lot of information, while most commercial apps are designed for beginners that only have a handful of smart devices to manage.

But back to the issue that is discussed here specifically: Here is a screen comparison for a typical page with text widgets:

<img width="478" alt="Bildschirm­foto 2023-01-31 um 23 35 23" src="https://user-images.githubusercontent.com/3244965/215899270-1db84084-1f92-4adf-bdb1-c120a2e2c8af.png">

I think this very clearly shows the inferior UX:
- Fonts are much smaller, making labels as well as values harder to read
- Less widgets fit onto the screen
- A lot of white space is on the screen
- Values are no longer "grouped" on the right, making it harder to compare and see them in combination.
- Values are not right-aligned, which makes it harder to spot their mutual proportions

> option to toggle between 'new' and 'old-ish' layout

If this is something that would work for you from a maintenance perspective, it might be a suitable compromise - but let's see with what you come up.

**Comment by maniac103** [comment] 2023-02-01 07:04
> In comparison to Google's own apps (e.g. "Home"), the font imho looks a bit too small now (and the toggles too huge in comparison to the font size):

The problem in that case is that Material Design advances too fast even for Google's own teams :roll_eyes: The screenshot of Home is MD2 (which is visible from the MD2 switch). If you look at e.g. Drive or Family Link, you'll see similar font sizes as in our new design.

> But there is, that's what I meant with "broken backwards compatibility". See e.g. these examples:

In both cases it's (at least partially) due to the new controls, though.

> Agreed, but I actually thought that for providing a huge flexibility, the feature to use the Main UI within the app had been added. As this gives huge freedom for everyone for custom layouts, I would think that the "classic" UX of openHAB, which exists since 12 years should only be carefully changed - and at least my impression is that long-term users really love the "cramped" design that makes efficient use of small screens. 

That's (IMO) oversimplified. I see at least 3 user groups, which may partially overlap:
- people who want simple configuration of their UI
- people who like crammed layouts
- people who want precise control over the widget look and feel

Main UI clearly is designed for the latter group. Needing to deal with CSS, YAML, HTML and so on clearly is a high entry hurdle, too high for new users or people from the first group. Those people (like for example me [1]) then use sitemaps to build their UI, because it's simple, but yet sufficient. That does *not* mean that all of those sitemap users belong to the second group (and I'm certainly not [the](https://community.openhab.org/t/new-look-for-sitemaps/143795/9) [only](https://github.com/openhab/openhab-android/issues/3159#issuecomment-1407650455) [person](https://github.com/openhab/openhab-android/issues/3159#issuecomment-1407768937)  who is part of the first, but not the second group)

[1] I have > 15 years of background in software development, so I consider myself not a technically unskilled person, but I really dislike having to deal with CSS and the like.

> This is actually something where I considered the openHAB apps always superior to any app from a "smart" manufacturer, because it is able to deal with lot of information, while most commercial apps are designed for beginners that only have a handful of smart devices to manage.

I'm not sure the equation `not using long pages of text in the UI == beginner` holds. To give one example: I have 103 things and 478 items (is this a beginner amount of devices?), but still don't have any such 'wall of text' as in the screenshot above. (I would put power & energy, voltages, currents, and 'everything else' each in their own frame, or even not show some of them at all. NB: why do you have a current flow of almost 1 amp without any voltage on P2?). YMMV, though, so whatever works for you is obviously fine. More on that screenshot below.

> I think this very clearly shows the inferior UX:

It's different, but I'd be careful with wording like 'inferior' or 'better', because...

> Fonts are much smaller, making labels as well as values harder to read
> Less widgets fit onto the screen
> A lot of white space is on the screen

... when are we going to redesign Basic UI?

![grafik](https://user-images.githubusercontent.com/781373/215970064-b1817faf-669f-45b1-b46d-ea61a4bb90c7.png)

Seriously though, what this image shows is that Basic UI has (and always had) similar amounts of whitespace and padding as the new design, and had even smaller font sizes. Yet I am not aware of any complaints about '[older people can't read it](https://github.com/openhab/openhab-android/issues/3159#issuecomment-1407477394)' or 'there's too much white space'. Why is that? For me, the only possible conclusion is 'it has always been that way, people don't know any different'. Since it looks like people can get equally used to the (old) Android app as well as the Basic UI design, there's nothing inherently  'inferior' or 'better'.

> Values are no longer "grouped" on the right, making it harder to compare and see them in combination.
> Values are not right-aligned, which makes it harder to spot their mutual proportions

Yes, comparing the values of 'Active Power' with 'Line Frequency' is harder now than before. Is this really a problem? Comparing the set of voltages (currents, powers) still works similarly well, because all 3 are in close proximity to each other.
But anyway, no need to argue about that case:

>  The idea we're currently pondering is one option to toggle between 'new' and 'old-ish' layout, where the latter means 'layout similar to before, just with new font sizes and padding'.

Closing remark: this app was started in 2012, and its look'n'feel basically stayed unchanged since then. Back then, Android looked like this:

![grafik](https://user-images.githubusercontent.com/781373/215973170-afe728b9-2288-4cad-b1a4-c7db9580c50f.png)

(Virtually) no design guides existed back then, so everybody basically just designed as they saw fit, which kinda is visible from the above screenshot already. The OH app design probably was a good fit back then, but look(ed) increasing dated with the advance of the design language in Android itself. We can not seriously take this 10 year old design as *the* silver bullet which nobody dare to touch again, be it font sizes, paddings or whatever - IMHO that is, at least. `Stillstand ist Rückschritt`. (Is there an English equivalent for that phrase?)

**Comment by kaikreuzer** [comment] 2023-02-01 07:42
> Basic UI has (and always had) similar amounts of whitespace and padding as the new design, and had even smaller font sizes. Yet I am not aware of any complaints about [...]. Why is that? For me, the only possible conclusion is 'it has always been that way

No, imho the reason is simply that Basic UI is not made for mobile devices, but for the PC with big screens. And the resolution of those screens are adapted to suit the users needs (and eyesight). Futhermore, in the browser it is very easy to adapt the font size with Ctrl-+/-. Would that maybe also be an option for the app (not through Ctrl+key, but in the settings)?

> Comparing the set of voltages (currents, powers) still works similarly well, because all 3 are in close proximity to each other.

... with other texts in between and no suitable alignment - I would not consider this "similarly well".

> (Virtually) no design guides existed back then, so everybody basically just designed as they saw fit, which kinda is visible from the above screenshot already

You should not mistake design guides for the launcher with the app's user interfaces. As mentioned [here](https://github.com/openhab/openhab-android/issues/3159#issuecomment-1410768305), I do not see ANY app that would even faintly adopt MD, maybe with the exception of a few apps from Google itself.

> We can not seriously take this 10 year old design as the silver bullet which nobody dare to touch again, be it font sizes, paddings or whatever

Imho we need to differentiate between "visual design", which is a kind of fashion and subject to personal taste and which needs to be updated once in a while to not look "angestaubt". As also mentioned [here](https://github.com/openhab/openhab-android/issues/3159#issuecomment-1410768305), I have absolutely nothing against an evolution here and it is clear that we will never meet everyone's taste, so I am also refraining from complaining about any parts of that (although I would prefer other headers, wish dividers back, etc., but I can live with such changes.)

But the point I think which needs discussion is the usability. And this is what my bullet point list from above was about and why I say that the update brings an inferior usability by not being easy to read for elderly (like me 😎 ) anymore, requiring the user to scroll more to see the same information, making it more difficult to read values (since tables are better to read simple lists), etc.

Imho we must not trade "fashion" against "usability" and it feels a bit that this is what happened here.
Just saying "Google said so" is no reason to break things that work smoothly. As said, I do not know any other app that strictly uses MD (or MD at all) and not adapt the UI to the specific needs of the application/user. This does not mean at all that I am asking for "stillstand", but to carefully weigh pros+cons to always increase the overall UX.

**Comment by kaikreuzer** [comment] 2023-02-01 09:50
> I'm not talking about the launcher. I'm talking about the vastly differing design languages in the various icons and especially homescreen widgets.

Yes, but I am talking about the UIs of the apps themselves and they are all very individual and following the own ideas and requirements of the respective app.

> You're free to use your power in the project 

No worries, I do not have any power in the project - you are the maintainers of the app and you decide. These are our rules and I do not question those. If I cannot live with changes, I'd have to create my own fork.

> I did just that, to the best of my knowledge.

Ok, then please let us come back to @mkrathome's original requirement: Tables are much much better to read than 2-line lists. Can we agree on this? We always had this feature and it would be a shame to drop it as I am sure it is used by many, many users. Just to give another example (a better curated one than the one from last night):

![Bildschirm­foto 2023-02-01 um 10 48 01](https://user-images.githubusercontent.com/3244965/216008717-55a68915-2366-47d7-bdd2-535564f06ccc.png)

What speaks against making the text widget in general show the value on the right and thus make it a 1-line cell?
This would be very much in line with the Switch widgets, which looks more or less the same with the only difference that the value is rendered as a toggle (but by this still shows the value).

**Comment by kaikreuzer** [comment] 2023-02-01 10:33
> -> https://github.com/maniac103/openhab.android/tree/compact-mode (which is what the above screenshots were taken with)

Ok, I stop quiet now and let you work. 😄

**Comment by mueller-ma** [comment] 2023-02-02 08:23
You can try out the code from #3177 with the following apk:

- Rename it to .apk
- Uninstall openHAB Beta if installed
- Install my apk

[openhab-compact.zip](https://github.com/openhab/openhab-android/files/10566770/openhab-compact.zip)

**Comment by dkneisz** [comment] 2023-02-02 09:22
I installed the beta version and activated compact mode. I think in case you have a switch with a value next to it, the value needs a little spacing:
![Screenshot_2023-02-02-10-16-01-47_fcd1c5899858d01174ac4962be56f19e](https://user-images.githubusercontent.com/43378003/216283190-a7c7e777-601b-4c99-8c66-ffe663a0a80d.jpg)
The rest looks good to me.

**Comment by mkrathome** [comment] 2023-02-02 11:29
> You can try out the code from #3177 with the following apk:
> 
> * Rename it to .apk
> * Uninstall openHAB Beta if installed
> * Install my apk
> 
> [openhab-compact.zip](https://github.com/openhab/openhab-android/files/10566770/openhab-compact.zip)

Hi and many many thanks that works perfekt for me, also the slider which opens at stepper cards ....in the meantime I love it  💕

The little padding on the left switch side, which @dkneisz  mentioned would be welcome, but I'm very happy now❤️

LG Manuel

**Comment by kaikreuzer** [comment] 2023-02-02 15:16
Nice work, indeed - many thanks!
I will have to get used to the smaller fonts (esp. for the values), but that'll happen.

The only issue I would like to ask you to address is the size of the slider - as you can see in the demo sitemap, it hardly leaves any space for the label text. If it would take roughly as much space as the steppers beneath it, it would imho be perfect:

![slider](https://user-images.githubusercontent.com/3244965/216363689-a30525a9-c8f1-46cf-b89d-9528c649f009.png)

**Comment by rkoshak** [comment] 2023-02-02 15:29
> Main UI clearly is designed for the latter group. Needing to deal with CSS, YAML, HTML and so on clearly is a high entry hurdle, too high for new users or people from the first group.

At the risk of veering off topic, I think this overstates the barriers to entry for using MainUI. It's not worth hashing out here unless these false assumptions are driving some decisions. 

People in your first group (people who want simple config of the UI) are also supported on MainUI. It's only that third group (people who want precise control over widget look and feel) who need to mess with CSS, YAML, or HTML. And even those users only rarely need to do so (and as more widgets get published even fewer people need that). Almost everything you have to deal with is through the Semantic Model or forms. No CSS. No YAML. No CSS.

But, your second group for sure (people who like crammed layouts) are not well served by MainUI.

I'm not arguing against sitemaps or anything like that. MainUI is not everyone's cup of tea. I just don't want the development of sitemaps and the android app to be driven by false impressions and assumptions about MainUI or for people to avoid MainUI with a false assumption about what it takes to use it.

> Yet I am not aware of any complaints about 'https://github.com/openhab/openhab-android/issues/3159#issuecomment-1407477394'

As one of those older people who can't read it, in the browser I can change the font size and pinch to zoom in BasicUI (and MainUI for that matter). I can't do this in the Android app as far as I can tell. And while I can adjust the font size through the OS (and the app conforms to those settings based on the discussion above), Android's font size choices are asinine. The penultimate size is just too small for me to read without glasses and the largest size is so big only about 15 characters fit on a line at a time. Pinch to zoom is a life saver in most places. 

Would that be worth filing a feature request on? Surely it's been requested before?

**Comment by Yogi4301** [comment] 2023-02-02 16:37
Nice work - thank you very much.

**Comment by Yogi4301** [comment] 2023-02-02 17:17
> You can try out the code from #3177 with the following apk:
> 
> * Rename it to .apk
> * Uninstall openHAB Beta if installed
> * Install my apk
> 
> [openhab-compact.zip](https://github.com/openhab/openhab-android/files/10566770/openhab-compact.zip)

Nice work - thank you very much!

**Comment by maniac103** [comment] 2023-02-02 19:35
> I'm not arguing against sitemaps or anything like that. MainUI is not everyone's cup of tea. I just don't want the development of sitemaps and the android app to be driven by false impressions and assumptions about MainUI or for people to avoid MainUI with a false assumption about what it takes to use it.

No worries. All that I wanted to say is that among the group of people who prefer sitemaps for whatever reason [1], there's different reasons for that preference, and 'crammed layout' is not the only possible reason. There isn't any more influence of that topic on Android app development than that ;-)

[1] Personal reason: I still find Main UI page configuration vastly more complicated than sitemap configuration though (I tried). Not sure whether it's because there's more docs on sitemaps, because I got accustomed to sitemaps since OH 1.6 (or something), or whether it's simply the price to pay for additional flexibility...after all, if there's no choices, one doesn't need to spend time on making a proper choice.

**Comment by mkrathome** [comment] 2023-02-02 20:08
> To give one example: I have 103 things and 478 items (is this a beginner amount of devices?), but still don't have any such 'wall of text' as in the screenshot

@maniac103 first of all many thanks again❤️

Funny: I looked up and found 101 things with 327 Items (not using every channel😉 only needed) at my live system. And yes I'm definitely a beginner started 9Month ago. After starting I checked out possibility  of UI and choose Sitemap. My personal focus is to control my equipment and spent as less time as possible. So maybe I belong to group [2] but i think Iits more that I like to use an UI which works for me and have not the need to be my living room.

All the best 🖖🏻 

Manuel

**Closed** 2023-02-03 07:22 UTC
Labels: bug

**Comment by alltime84** [comment] 2023-02-03 08:15
Nice! Thanks a lot for the new options!
What I like most in the initial design is the new Setpoint Widget. It can replace the Slider completely.
Would it be possible to use the new Setpoint also in Compact Mode? Maybe even a vertical slider? There is space enough in the popup.

**Comment by alltime84** [comment] 2023-02-03 08:22
> > Would it be possible to use the new Setpoint also in Compact Mode?
> 
> What do you mean here? I assume you haven't touched the full row? ;-)

Oh, yes. Great! I never touched it. I thought it is not available as there are no arrows up and down anymore.

**Comment by maniac103** [comment] 2023-02-03 08:25
> I thought it is not available as there are no arrows up and down anymore.

Yes, non-discoverability was an issue we thought about ... it's always a trade-off between that and screen estate usage.

**Comment by kaikreuzer** [comment] 2023-02-04 22:39
Nice result, I like it a lot - thanks for the compact mode, @maniac103 and @mueller-ma!
