### ISSUE TITLE
Let's Encrypt Certificate has to be accepted manually

### ISSUE THREAD

**Issue by Confectrician** [openhab/openhab-android#2341] opened 2020-12-23 07:48 UTC
### Actual behaviour
When i connect an openHAB instance secured with a Let's Encrypt Certificate (via NGINX reverse proxy).
I will get a message that the certificate is not issued by a trusted authority.
I can accept the certificate then manuall and the connection is established.

*(I can provide a mobile screenshot, if needed but writing on PC currently. Just ping me.)*

### Expected behaviour
I would assume tha Let's Encrypt is a trsuted authority and so a connection like described above should be configurable without a warning and manual intervention (accepting the certificate).

 
### Steps to reproduce
1. Set up an openHAB 3 instance with NGINX Reverse Proxy and a Let's Encrypt ssl certificate
2. Configure a connection to this server in the app

### Can you reproduce the issue in demo mode?
No.

#### Client
* Android version: 10
* Device model: OnePlus Nord
* App version : 2.15.15-beta
* Build flavor : FUll
* Device language: German

#### Server
* Server version: openHAB 3.0.0 Stable Release
* Reverse Proxy: NGINX with Let's Encrypt Certificate
* Authentication method : User and Password

#### openHAB Cloud
No

#### App log
-

#### openHAB Server log
-

**Comment by mueller-ma** [comment] 2020-12-23 08:48
Does it work without any warning in a browser (PC and mobile)?

**Comment by Confectrician** [comment] 2020-12-23 09:16
Yes worked flawless directly after setting it up.

![image](https://user-images.githubusercontent.com/7161177/102980383-c9f07a00-4507-11eb-94a4-30875a04aff7.png)
![image](https://user-images.githubusercontent.com/7161177/102980449-decd0d80-4507-11eb-8cd3-bb49b6205358.png)

**Comment by mueller-ma** [comment] 2020-12-23 12:00
These screenshots were done on Windows, right? Can you check it in a browser on your phone? Preferable a pre-installed browser or chrome.

**Comment by Confectrician** [comment] 2020-12-23 23:16
Of course. Checked and it is working fine.
I am using the main Ui as app for some days already.

![Screenshot_20201224-001443.jpg](https://user-images.githubusercontent.com/7161177/103043486-496c6080-457d-11eb-8f8e-346674a7eec6.jpg)

**Comment by Confectrician** [comment] 2020-12-23 23:20
Here is the warning to have everything at place.

![Screenshot_20201223-082741__01.jpg](https://user-images.githubusercontent.com/7161177/103043641-dca59600-457d-11eb-8a9f-9b8732c3dce7.jpg)

**Comment by mueller-ma** [comment] 2020-12-27 21:39
The demo server also uses Let's encrypt and the handshake is working there. (The demo mode is broken, but the issue is after the handshake).
I read some news about Let's encrypt moving to their own root certificate. Can you try to renew your cert?

**Comment by Confectrician** [comment] 2020-12-28 07:57
Yes i can try that.

Just as additional input. I checked the demo server and it has the same root certificate as mine.

**Comment by mueller-ma** [comment] 2021-01-24 22:04
@Confectrician Can you install the latest beta (https://github.com/openhab/openhab-android/releases/tag/2.15.24-beta) and check if the demo mode is working on your device?

**Comment by Confectrician** [comment] 2021-01-27 20:44
Auto update did that for me already. 
Demo mode seems to be working fine.

I could activate and play around a bit without any error.
I think i have also refreshed the certificate meanwhile. But probably my decision to trust the certificate was cached somewhere.

**Comment by mueller-ma** [comment] 2021-01-27 21:11
Demo mode is also working for me, so there should be no general issue with Let's encrypt. 

> But probably my decision to trust the certificate was cached somewhere.

Yes, it's cached until you reinstall the app.

**Closed by mueller-ma** 2021-01-27 21:11 UTC
Labels: bug
