### ISSUE TITLE
Support for Android Wear 2.0 

### ISSUE THREAD

**Issue by LuggyLuke** [openhab/openhab-android#1106] opened 2018-11-21 12:31 UTC
So i just Installed the app on my wear os watch and it actually works pretty great. (tutorials how to install using adb can be found with google). In contrast to the old Issues #73 and #381.
One tiny setback is the use of bluetooth tethering between watch and smartphone. This type of network connection seems to be pretty new and cant be handled by the app. Changing the determineAvailableConnection function should fix it and hopefully its still possible to access the servers. So the details: 
Smartwach with only Wlan enabled -- App works as expected.
Smartwatch with Bluetooth (and Wlan) enabled -- App wont start because the NetworkInfo.getType() returns unexpected value (COMPANION_PROXY).
so either adding COMPANION_PROXY to the list of expected networktypes or updating the whole NetworkInfo class to the new NetworkCapabilities class should fix it. 

(this is my first issue post and i am also new to github so please be forgiving for my countless mistakes i made here :-))

**Comment by maniac103** [comment] 2018-11-21 15:01
The deprecation is irrelevant here, because it's deprecated only in API 28 (Android 9.0) and getType is still fine for being used on older API levels. NetworkCapabilities also only exists for API >= 21.

Where does that COMPANION_PROXY name come from? AFAICT it's not listed in the docs: https://developer.android.com/reference/android/net/ConnectivityManager

**Comment by LuggyLuke** [comment] 2018-11-21 15:14
COMPANION_PROXY seems to be a special value used in wear os smartwatches when they get their network connection via bluetooth. But its weird that there is no documentation for that :-(.

**Comment by maniac103** [comment] 2018-11-21 15:55
I guessed so, but given the types are ints, you must have got that name from somewhere ... my question was where exactly you got it from? Also, what's the numerical value for it?

**Comment by LuggyLuke** [comment] 2018-11-21 16:07
Ahhh. I got it ftom the app, it says network not supported (netzwerkfehler) and then prints the getinfo of the network. Which shows as COMPANION_PROXY.

**Comment by maniac103** [comment] 2018-11-21 18:11
Can you make a screenshot of that?

**Comment by LuggyLuke** [comment] 2018-11-22 09:09
Here is a Picture, hopefully it helps. I tried modding the apk to start a connection on any type of network, but it seems it cant find the ip while using the bluetooth connection. so there might not be an easy way getting this to work.
![companion_proxy](https://user-images.githubusercontent.com/45229887/48892603-bbbe6400-ee3e-11e8-8682-290a3f8402e4.jpg)

**Comment by LuggyLuke** [comment] 2018-11-22 12:10
ok so i got a test app working using the example from https://developer.android.com/training/wearables/data-layer/network-access#java. i am not sure how to link my fork or add the app as a release but i will check, so if anyone finds this he can give it a try. Until someone with real knowhow can create a cleaner solution.

**Comment by LuggyLuke** [comment] 2018-12-03 06:55
Well first there would need be a proper wear app, right now my fork is just the basic android app without any real changes. I am no android programmer so i dont think i will be able to port it to wear anytime soon, but if you want to give it a try i would be happy to help :-). Maybe now there are actually enough people with watches to justify development.

**Comment by mueller-ma** [comment] 2019-08-29 19:07
Duplicate of #73.

**Closed by mueller-ma** 2019-08-29 19:07 UTC
Labels: enhancement
