### ISSUE TITLE
Secondary remote conection as backup

### ISSUE THREAD

**Issue by magd1978** [openhab/openhab-android#1100] opened 2018-11-16 12:21 UTC
As a result of the latest problems with the openHAB cloud service, it occurred to me that it might be possible to add a secondary remote connection that acts as a backup of the main one, so that if temporarily it was not possible to connect through the main connection (example: myopenhab.org), a "direct" secondary connection to the host could be established (example: through public IP and redirected port to openHAB instance with NGINX reverse proxy).

I already set a reverse proxy, and I can directly connect the APP to my openHAB instance by open port exposed in public IP. But I prefer to connect the APP through myopenhab in order to receive push notifications.

I would like to automate this switching of config when cloud service will be down. That is why I propose to add one more field in the APP configuration that allows defining an alternative external connection that serves as a backup if the main one is not available.

There is a post about it in the following link of community forum:
[https://community.openhab.org/t/secondary-remote-conection-as-backup/56787](https://community.openhab.org/t/secondary-remote-conection-as-backup/56787)

**Comment by mueller-ma** [comment] 2018-12-01 11:59
Kind of duplicate of https://github.com/openhab/openhab-android/issues/10

**Closed by mueller-ma** 2018-12-01 11:59 UTC
