### ISSUE TITLE
Network not available error

### ISSUE THREAD

**Issue by Vegardbeider** [openhab/openhab-android#2488] opened 2021-03-17 10:06 UTC
### Actual behaviour
Network not available error when trying to connect away from home

### Expected behaviour
Use remote url to connect 

 
### Steps to reproduce
1. Add both local and remote url
2. Try connect when not home(through remote url) it says network not available. It tries to connect with the local url for very long before it jumps over to remote url 

### Can you reproduce the issue in demo mode?

No

#### Client
* Android version: 11
* Device model: Samsung Galaxy S10e
* App version : 2.16.0
* Build flavor : 
* Device language: 
Norwegian /English 
#### Server
* Server version: OH 2.4.0
* Reverse Proxy: yes
* Authentication method : user name and password

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: slef hosted
* openHAB Cloud version : 
* Authentication method : 

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>

#### openHAB Server log
<details>
  <summary>Click to expand</summary>

```
Not required.
If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

</details>

**Comment by mueller-ma** [comment] 2021-03-17 11:28
Could this be #898? The issue is still present, but closed in this repo, because it's an issue of the connector.

**Comment by Vegardbeider** [comment] 2021-03-17 11:37
No I don't think it can be server side issue. It happened after the latest app update in February. I have been using the last month or so to figgure out what the problem could be. I have a second OH instance, same version on my cabin and got same problem there. The problem stops when I remove the local url, them it jumps straight to remote url. So to me it seams that it want to connect using the local url and uses many tries at that before it tries the remote one.

**Comment by maniac103** [comment] 2021-03-17 11:59
What kinds of networks do you have connected at that time? May a VPN be active?

**Comment by Vegardbeider** [comment] 2021-03-17 12:04
No VPN, it's either work wifi, friends wifi or mobile data 4G LTE

**Comment by Vegardbeider** [comment] 2021-03-17 12:04
The local ip address for my device when on work wifi is completely different to my home network (where my OH is at)

**Comment by maniac103** [comment] 2021-03-17 12:16
Well, as long as you're connected to WiFi, it's expected for the local connection to be tried first. The local server isn't 'bound' to a WiFi SSID, and I'm really not sure whether adding a feature that allows for such binding wouldn't introduce more issues and confusion than it helps.

**Comment by Vegardbeider** [comment] 2021-03-17 12:39
No iam not after a feature like that. I thnik that would make more trouble then it solves. But I would assume the app is supposed to try remote url by it self after failing on local not just leave the error network not available message. Before it worked without problem. But as I said after the update in February the error came to life

**Comment by mueller-ma** [comment] 2021-08-29 15:11
Sounds like a duplicate of #146 to me.

**Closed by mueller-ma** 2021-08-29 15:11 UTC
Labels: bug
