### ISSUE TITLE
Notifications sent to wrong user in local network.

### ISSUE THREAD

**Issue by magd1978** [openhab/openhab-android#657] opened 2018-01-20 00:27 UTC
I detected a curious issue receiving notifications in the local network. I used to have a login / password for the reverse proxy nginx (local access) and it was the same credentials for myopenhab. I added new users to myopenhub to send different messages to different users, and changed in app the login / password for remote access to one of the newly created ones. Now I get the messages addressed to the new user when I'm connected remotely, and those addressed to the old user when I connect locally. When local access is available, the app will use the local login / password to receive messages from the cloud, and I think that this is wrong (no local credentials, no messages). The app should always use the credentials for remote access.

**Comment by FlorianSW** [comment] 2018-01-23 18:39
Would probably be fixed by #562, as it will have it's dedicated "CLOUD" connection for the notifications, which currently is an alias for the remote settings connection data.

**Comment by mueller-ma** [comment] 2018-03-31 07:19
@magd1978 Can you download the latest beta and check if the issue is still present? https://github.com/openhab/openhab-android/releases

**Comment by magd1978** [comment] 2018-03-31 09:07
2.0.43-beta seems to have solved the bug.
However. I found a different little bug: When you configure openHab beta settings, if you tell it to ignore SSL certificate and domain, the value is not applied until you completely close the application from the task manager and reopen it.

**Closed** 2018-03-31 09:07 UTC
Labels: awaiting feedback, bug
