### ISSUE TITLE
No possibility to close fullscreen of MapView-Widget

### ISSUE THREAD

**Issue by alltime84** [openhab/openhab-android#3261] opened 2023-02-22 09:36 UTC
Hi!

If I click on a MapView-Widget it opens in full screen. But I do not find a possibility how to close it again.
Is it a bug or do I just not know how?

![Screenshot (22 02 2023 10_29_14) 2023 10_29_14)](https://user-images.githubusercontent.com/15026656/220579683-e0b8833c-2265-4aac-b0d3-8b6dce22cd93.png)

**Comment by maniac103** [comment] 2023-02-22 09:55
Back button / gesture helps ;-)

**Comment by alltime84** [comment] 2023-02-22 09:57
Hmm, the back-gesture closes the whole app and not only the popup...

**Comment by maniac103** [comment] 2023-02-22 10:12
It definitely doesn't do that for me?!

**Comment by alltime84** [comment] 2023-02-22 12:29
Hmm, how should I prove that?
I have a Pixel 6 with the latest Android-Version.
Also changing from gesture to button causes the same issue.

Also Android is telling me that the app was stopped repeatedly when I try the same twice.

**Comment by maniac103** [comment] 2023-02-22 12:59
> Also Android is telling me that the app was stopped repeatedly when I try the same twice.

That rather sounds like the app crashed when you did the back gesture (which gives the same effect as if the app was closed). I wonder whether it's the same thing as #3237.

**Comment by alltime84** [comment] 2023-02-22 16:21
This is from the log:
```
-----------------------
Device information
Model: Pixel 6
Manufacturer: Google
Brand: google
Device: oriole
Product: oriole
OS: 13
Display: 1080x2219, 2.625 density
Data usage policy: DataUsagePolicy(canDoLargeTransfers=true, loadIconsWithState=true, autoPlayVideos=true, canDoRefreshes=true), data saver: 1, battery saver: false
-----------------------

--------- beginning of crash
02-22 13:33:52.026  8918  8918 E AndroidRuntime: FATAL EXCEPTION: main
02-22 13:33:52.026  8918  8918 E AndroidRuntime: Process: org.openhab.habdroid, PID: 8918
02-22 13:33:52.026  8918  8918 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.br.w()' on a null object reference
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at com.google.maps.api.android.lib6.impl.cw.i(:com.google.android.gms.dynamite_mapsdynamite@230514044@23.05.14 (190400-0):0)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at com.google.android.gms.maps.internal.q.bb(:com.google.android.gms.dynamite_mapsdynamite@230514044@23.05.14 (190400-0):17)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at fg.onTransact(:com.google.android.gms.dynamite_mapsdynamite@230514044@23.05.14 (190400-0):4)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at android.os.Binder.transact(Binder.java:1164)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at com.google.android.gms.maps.internal.zzl.onPause(com.google.android.gms:play-services-maps@@18.1.0:2)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at com.google.android.gms.maps.zzag.onPause(com.google.android.gms:play-services-maps@@18.1.0:1)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at com.google.android.gms.dynamic.DeferredLifecycleHelper.onPause(com.google.android.gms:play-services-base@@18.0.1:1)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at com.google.android.gms.maps.MapView.onPause(com.google.android.gms:play-services-maps@@18.1.0:1)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at org.openhab.habdroid.ui.MapBottomSheet.onPause(MapViewHelper.kt:175)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at androidx.fragment.app.Fragment.performPause(Fragment.java:3305)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:631)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:293)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:942)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:201)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at android.os.Looper.loop(Looper.java:288)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7872)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-22 13:33:52.026  8918  8918 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: FATAL EXCEPTION: main
02-22 13:34:01.518  9614  9614 E AndroidRuntime: Process: org.openhab.habdroid, PID: 9614
02-22 13:34:01.518  9614  9614 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.br.w()' on a null object reference
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at com.google.maps.api.android.lib6.impl.cw.i(:com.google.android.gms.dynamite_mapsdynamite@230514044@23.05.14 (190400-0):0)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at com.google.android.gms.maps.internal.q.bb(:com.google.android.gms.dynamite_mapsdynamite@230514044@23.05.14 (190400-0):17)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at fg.onTransact(:com.google.android.gms.dynamite_mapsdynamite@230514044@23.05.14 (190400-0):4)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at android.os.Binder.transact(Binder.java:1164)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at com.google.android.gms.maps.internal.zzl.onPause(com.google.android.gms:play-services-maps@@18.1.0:2)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at com.google.android.gms.maps.zzag.onPause(com.google.android.gms:play-services-maps@@18.1.0:1)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at com.google.android.gms.dynamic.DeferredLifecycleHelper.onPause(com.google.android.gms:play-services-base@@18.0.1:1)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at com.google.android.gms.maps.MapView.onPause(com.google.android.gms:play-services-maps@@18.1.0:1)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at org.openhab.habdroid.ui.MapBottomSheet.onPause(MapViewHelper.kt:175)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at androidx.fragment.app.Fragment.performPause(Fragment.java:3305)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:631)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:293)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:942)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:201)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at android.os.Looper.loop(Looper.java:288)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7872)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-22 13:34:01.518  9614  9614 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: FATAL EXCEPTION: main
02-22 13:35:08.876 10880 10880 E AndroidRuntime: Process: org.openhab.habdroid, PID: 10880
02-22 13:35:08.876 10880 10880 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.br.w()' on a null object reference
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at com.google.maps.api.android.lib6.impl.cw.i(:com.google.android.gms.dynamite_mapsdynamite@230514044@23.05.14 (190400-0):0)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at com.google.android.gms.maps.internal.q.bb(:com.google.android.gms.dynamite_mapsdynamite@230514044@23.05.14 (190400-0):17)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at fg.onTransact(:com.google.android.gms.dynamite_mapsdynamite@230514044@23.05.14 (190400-0):4)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at android.os.Binder.transact(Binder.java:1164)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at com.google.android.gms.maps.internal.zzl.onPause(com.google.android.gms:play-services-maps@@18.1.0:2)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at com.google.android.gms.maps.zzag.onPause(com.google.android.gms:play-services-maps@@18.1.0:1)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at com.google.android.gms.dynamic.DeferredLifecycleHelper.onPause(com.google.android.gms:play-services-base@@18.0.1:1)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at com.google.android.gms.maps.MapView.onPause(com.google.android.gms:play-services-maps@@18.1.0:1)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at org.openhab.habdroid.ui.MapBottomSheet.onPause(MapViewHelper.kt:175)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at androidx.fragment.app.Fragment.performPause(Fragment.java:3305)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:631)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:293)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:942)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:201)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at android.os.Looper.loop(Looper.java:288)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7872)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-22 13:35:08.876 10880 10880 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
--------- beginning of main
02-22 17:11:42.270  2801  2823 E BLASTBufferQueue: [VRI[MainActivity]#3](f:0,a:4) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:11:42.279  2801  2823 E BLASTBufferQueue: [VRI[MainActivity]#3](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:11:42.296  2801  2823 E BLASTBufferQueue: [VRI[MainActivity]#3](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:11:58.143  2801  2820 E BLASTBufferQueue: [VRI[MainActivity]#3](f:0,a:4) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:11:58.159  2801  2820 E BLASTBufferQueue: [VRI[MainActivity]#3](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:11:58.177  2801  2820 E BLASTBufferQueue: [VRI[MainActivity]#3](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:11:58.202  2801  2820 E BLASTBufferQueue: [VRI[MainActivity]#3](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:11:58.220  2801  2820 E BLASTBufferQueue: [VRI[MainActivity]#3](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:22.964  2801  2823 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:22.969  2801  2823 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.276  2801  2978 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.288  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.304  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.330  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.346  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.361  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.379  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.396  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.413  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.430  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.447  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.462  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.484  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.545  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.564  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.580  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.593  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.611  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.629  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.646  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.661  2801  5172 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.679  2801  2978 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.693  2801  2978 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.710  2801  2978 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.730  2801  2978 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.744  2801  2978 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.762  2801  2978 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.777  2801  2978 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.798  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:30.812  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.410  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.424  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.442  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.457  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.475  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.491  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.508  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.524  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.542  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.558  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.574  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.590  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.609  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.623  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.642  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.658  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:31.678  2801 12966 E BLASTBufferQueue: [VRI[PreferencesActivity]#4](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:13:59.669  2801  2822 E BLASTBufferQueue: [VRI[PreferencesActivity]#7](f:0,a:4) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:14:10.044  2801  2801 E SurfaceSyncer: Failed to find sync for id=0
02-22 17:14:12.024  2801  2801 E AndroidRuntime: FATAL EXCEPTION: main
02-22 17:14:12.024  2801  2801 E AndroidRuntime: Process: org.openhab.habdroid, PID: 2801
02-22 17:14:12.024  2801  2801 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.br.w()' on a null object reference
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at com.google.maps.api.android.lib6.impl.cw.i(:com.google.android.gms.dynamite_mapsdynamite@230514044@23.05.14 (190400-0):0)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at com.google.android.gms.maps.internal.q.bb(:com.google.android.gms.dynamite_mapsdynamite@230514044@23.05.14 (190400-0):17)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at fg.onTransact(:com.google.android.gms.dynamite_mapsdynamite@230514044@23.05.14 (190400-0):4)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at android.os.Binder.transact(Binder.java:1164)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at com.google.android.gms.maps.internal.zzl.onPause(com.google.android.gms:play-services-maps@@18.1.0:2)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at com.google.android.gms.maps.zzag.onPause(com.google.android.gms:play-services-maps@@18.1.0:1)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at com.google.android.gms.dynamic.DeferredLifecycleHelper.onPause(com.google.android.gms:play-services-base@@18.0.1:1)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at com.google.android.gms.maps.MapView.onPause(com.google.android.gms:play-services-maps@@18.1.0:1)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at org.openhab.habdroid.ui.MapBottomSheet.onPause(MapViewHelper.kt:175)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at androidx.fragment.app.Fragment.performPause(Fragment.java:3305)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:631)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:293)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1823)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:942)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:201)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at android.os.Looper.loop(Looper.java:288)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7872)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-22 17:14:12.024  2801  2801 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
02-22 17:14:13.212 14194 14194 E penhab.habdroid: Not starting debugger since process cannot load the jdwp agent.
02-22 17:15:01.816 14194 14208 E BLASTBufferQueue: [VRI[LogActivity]#2](f:0,a:4) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:15:01.821 14194 14208 E BLASTBufferQueue: [VRI[LogActivity]#2](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:15:01.838 14194 14208 E BLASTBufferQueue: [VRI[LogActivity]#2](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:15:01.856 14194 14208 E BLASTBufferQueue: [VRI[LogActivity]#2](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:15:01.881 14194 14208 E BLASTBufferQueue: [VRI[LogActivity]#2](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:15:01.897 14194 14208 E BLASTBufferQueue: [VRI[LogActivity]#2](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:15:01.913 14194 14208 E BLASTBufferQueue: [VRI[LogActivity]#2](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:15:01.931 14194 14208 E BLASTBufferQueue: [VRI[LogActivity]#2](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:15:11.873 14194 14206 E BLASTBufferQueue: [VRI[LogActivity]#2](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:15:11.884 14194 14206 E BLASTBufferQueue: [VRI[LogActivity]#2](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:15:11.901 14194 14206 E BLASTBufferQueue: [VRI[LogActivity]#2](f:0,a:3) Faking releaseBufferCallback from transactionCompleteCallback
02-22 17:15:11.924 14194 14206 E BLASTBufferQueue: [VRI[LogActivity]#2](f:0,a:2) Faking releaseBufferCallback from transactionCompleteCallback
```

**Comment by maniac103** [comment] 2023-02-22 16:28
Yep, that's #3237.

**Comment by mueller-ma** [comment] 2023-02-23 09:35
Closing as duplicate of #3237.

**Closed by mueller-ma** 2023-02-23 09:35 UTC
Labels: bug
