### ISSUE TITLE
remote openhab-cloud instance + Android App: cannot load sitemap in app only

### ISSUE THREAD

**Issue by ScheissSchiesser** [openhab/openhab-android#674] opened 2018-01-26 20:22 UTC
I am running openhab 2.2 snapshot and a dockerized instance of _openhab-cloud_.

My _openhab-cloud_ instance is accessible via an opened port from my router and a URL supplied by a DDNS service.

I can access _openhab-cloud_ via `http://<my-domain>.com:8000` in a browser

I can access my openhab sitemaps via `http://<my-domain>.com:8000/basicui/app?sitemap=default`

When I enter `http://<my-domain>.com:8000` and my username and password for _openhab-cloud_ into the android app, I can successfully connect to the _openhab-cloud_ instance and receive android notifications. However, the app does not successfully load the sitemap or give me any kind of error message. The loading icon in the upper right corner continuously refreshes, but never finishes.

Is this a bug, or is there something I am missing?

**Comment by mueller-ma** [comment] 2018-01-26 20:45
> When I enter http://<my-domain>.com:8000 and my username and password for openhab-cloud into the android app

You entered them under "Remote"?

> or is there something I am missing?

Entering url, user and pw is enough. Can you capture a debug log via logcat?

**Comment by ScheissSchiesser** [comment] 2018-01-26 21:07
Forgive me, but is there an easier way than [using android studio to capture logs with logcat](https://developer.android.com/studio/debug/am-logcat.html)? Can I capture logs with an android app without needing to install android studio?

**Comment by maniac103** [comment] 2018-01-26 21:11
If your device is rooted, you can use MatLog:

**Comment by ScheissSchiesser** [comment] 2018-01-26 21:27
[openhablog.txt](https://github.com/openhab/openhab-android/files/1669238/openhablog.txt)

None of this looks relevant to me, but hopefully it makes sense to you...

I used a terminal emulator on my phone to start `logcat` and sent the output to a file, then opened the Openhab app, tried to load the default sitemap, and then closed `logcat`. I've attached the output.

**Comment by maniac103** [comment] 2018-01-26 21:58
Running `logcat` in a terminal app doesn't work, as it'll capture the output of the terminal app only. The only workable way is using an app like MatLog or via ADB on PC (don't need full Android Studio, there are ADB-only ZIPs available for Windows IIRC; for Linux ADB is often packaged by the distributions)

**Comment by ScheissSchiesser** [comment] 2018-01-26 22:42
See below for a proper logcat through ADB. Looks like the openhab android app is requesting the sitemap from the wrong endpoint? Shouldn't that be `/default/` not `/default/default/` ?
```
E/OpenHABWidgetListFragment(17930): java.io.IOException: Not Found
E/OpenHABWidgetListFragment(17930): status code = 404
E/OpenHABWidgetListFragment(17930): Connection error = class java.io.IOException, cycle aborted
I/OpenHABWidgetListFragment(17930):  showPage for http://[MY-DOMAIN-REDACTED].com/rest/sitemaps/default/default longPolling = false
D/OpenHABWidgetListFragment(17930): isAdded = true
D/OpenHABWidgetListFragment(17930): Start progress indicator
D/OpenHABWidgetListFragment(17930): Stop progress indicator
E/OpenHABWidgetListFragment(17930): java.io.IOException: Not Found
E/OpenHABWidgetListFragment(17930): status code = 404
E/OpenHABWidgetListFragment(17930): Connection error = class java.io.IOException, cycle aborted
I/OpenHABWidgetListFragment(17930):  showPage for http://[MY-DOMAIN-REDACTED].com/rest/sitemaps/default/default longPolling = false
```

**Comment by mueller-ma** [comment] 2018-01-26 22:57
Are you running a different webserver on port 80?

**Comment by ScheissSchiesser** [comment] 2018-01-26 23:46
I am, unfortunately.

**Comment by mueller-ma** [comment] 2018-01-27 11:26
> Most importantly, it is not respecting the port number

Cannot confirm that. I have a oh test installation on port 8080 and a reverse proxy with basic authentication on port 80. I can see in the log, that the I'm entering is requested.

**Comment by FlorianSW** [comment] 2018-01-27 13:21
So, testing with `http://test.com:8000` in the remote settings I can see, that the app tries to connect to the host test.com on port 8000 (which obviously fails, of course). So, please excuse this probably dumb question: Do you really have entered the correct URL in your connection settings? (Could you probably post a screenshot of it, even if it reveals the public URL of your openhab-cloud instance, so it would be ok, if you do not want to do that).

One more question: Have you installed the app from the Google Play store or from F-DROID or have yu built it on your own?

**Comment by mueller-ma** [comment] 2018-01-27 13:28
FYI currently the foss version contains crashalytics (See #482) and until that is resolved, fdroid wont publish the foss apk.

**Comment by ScheissSchiesser** [comment] 2018-01-27 19:07
> So, please excuse this probably dumb question: Do you really have entered the correct URL in your connection settings?

A fair question! See below. I've redacted my info.

![screenshot_2018-01-27-13-55-00-1](https://user-images.githubusercontent.com/9285100/35475334-8c273b96-036a-11e8-84d3-a9907a8a3a42.jpg)

Trailing slash makes no difference to this problem.

> Have you installed the app from the Google Play store or from F-DROID or have you built it on your own?

Installed from google play store.

I am going to take my other webpage at port 80 offline and see if openhab-cloud works on port 80.

**Comment by ScheissSchiesser** [comment] 2018-01-27 19:23
I can confirm that the app works as expected when running openhab-cloud on port 80 (with no port specified in the app settings).

I am starting to think the problem is coming from the nginx configuration of the openhab-cloud docker image. It seems like that is not reporting the correct URL through REST. E.g.:

Visiting `http://[MY-DOMAIN].com:8000/rest/sitemaps` returns 
`[{"name":"default","label":"My Home","link":"http://[MY-DOMAIN].com/rest/sitemaps/default","homepage":{"link":"http://[MY-DOMAIN].com/rest/sitemaps/default/default","leaf":false,"widgets":[]}},{"name":"presence","label":"Presence Sensors","link":"http://[MY-DOMAIN].com/rest/sitemaps/presence","homepage":{"link":"http://[MY-DOMAIN].com/rest/sitemaps/presence/presence","leaf":false,"widgets":[]}},{"name":"_default","label":"Home","link":"http://[MY-DOMAIN].com/rest/sitemaps/_default","homepage":{"link":"http://[MY-DOMAIN].com/rest/sitemaps/_default/_default","leaf":false,"widgets":[]}}]`

**Comment by mueller-ma** [comment] 2018-01-27 20:24
I have very limited knowledge of nginx, but I assume it works similar to apache. In apache you have a setting called "servername". Try to add port 8000 to this setting.

**Comment by ScheissSchiesser** [comment] 2018-01-30 17:05
> In apache you have a setting called "servername". Try to add port 8000 to this setting.

I don't have high hopes for this. I'm not sure that would affect the REST API call, would it? I will try it...

**Comment by mueller-ma** [comment] 2018-01-30 17:36
openHAB has to determine somehow which url it should use. As I did never configure any URL in openhab, I think it get the information from the webserver.

**Comment by rapiertg** [comment] 2018-02-01 19:51
I have exactly the same behavior. On cloud connector logs I am getting 401 spam after some 200 GET's:
`GET /api/v1/settings/notifications 200 112.917 ms - 32
GET /rest/bindings 200 141.173 ms - 2319
GET /rest/sitemaps 200 49.301 ms - 403
GET /rest/sitemaps/_default/_default 401 2.500 ms - -
GET /rest/sitemaps/_default/_default 401 1.105 ms - -
GET /rest/sitemaps/_default/_default 401 1.274 ms - -
GET /rest/sitemaps/_default/_default 401 1.046 ms - -
GET /rest/sitemaps/_default/_default 401 1.107 ms - -
GET /rest/sitemaps/_default/_default 401 1.196 ms - -
GET /rest/sitemaps/_default/_default 401 1.109 ms - -
GET /rest/sitemaps/_default/_default 401 1.264 ms - -
GET /rest/sitemaps/_default/_default 401 1.157 ms - -
`

**Comment by BenPru** [comment] 2018-02-27 21:31
I think I have the same problem.
I have a apache reverse proxy. My URL is https://mydomain/oh
This is not working because the app doesn't use the sub-path at all. In the apache logs I can see the following wrong path requests:
/addAndroidRegistration?deviceId=... with http status 404 - instead of /oh/addAndroidRegistration?deviceId=
/rest/ instead of /oh/rest/
/api/v1/settings/notifications instead of /oh/api/v1/settings/notifications

After changing the reverse proxy - with the exact same config! - from port 443 and subpath oh to port 8443 without a subpath - all is working fine.
But many firewall are blocking 8443 and I would like to use 443 with a sub path.

**Comment by dastrix80** [comment] 2018-09-04 10:30
Ihave the same problem, cant access Openhab Cloud using the Android App and using a local instance of OH2 Cloud.

It runs on 3000 by default. I can hit the webpage on 3000 but my Android wont display the sitemaps!

What can I do?

**Comment by mystdeim** [comment] 2019-05-30 20:07
I can confirm the same issue. I have nginx in front of my openhab cloud instance on 443 port with https. 
I see requests in access.log but my android app show me empty screen

**Comment by gishanc** [comment] 2019-10-10 04:22
This should be a bug. Android app does not use the URL given in settings. It is always calling the port 8080 to fetch the sitemap. This is seen in app log. This is a big problem. I cannot block port 8080 in firewall. I have password protected nginx on port 443 which cannot be used with app.

**Comment by mueller-ma** [comment] 2019-10-21 18:19
I found the issue. I have configured two nginx vservers on different ports:
````
server {
    listen                                    81;
    server_name                               openhab2.local;

    location / {
        proxy_pass                            http://localhost:8080/;
        proxy_set_header Host                 $http_host;
        proxy_set_header X-Real-IP            $remote_addr;
        proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto    $scheme;
        auth_basic                            "Username and Password Required";
        auth_basic_user_file                  /etc/nginx/.htpasswd;
    }
}

server {
    listen                                    82;
    server_name                               openhab2.local;

    location / {
        proxy_pass                            http://localhost:8080/;
        auth_basic                            "Username and Password Required";
        auth_basic_user_file                  /etc/nginx/.htpasswd;
    }
}

````

If I connect to port 81 and go to `/rest`, the url of e.g. "voice" is "http://openhab2.local:81/rest/voice" (url + port of reverse proxy).
If I connect to port 82 and go to the same url, the url of "voice" is "http://localhost:8080/rest/voice" (url + port of the openHAB server).

I can think of "fixing" this by forcing the port configured in the settings instead of the port the rest api returns. However this can be fixed by fixing the reverse proxy configuration.

**Comment by gishanc** [comment] 2019-10-22 06:19
Thanks for looking into this. I fixed it this way. Since this can be fixed through configuration i dont think a fix on app is needed at this point.

**Comment by mueller-ma** [comment] 2019-10-22 18:39
If anyone also has this issue, please post your reverse proxy configuration.

**Closed by mueller-ma** 2019-10-22 18:39 UTC
Labels: bug

**Comment by ScheissSchiesser** [comment] 2019-10-26 03:51
@mueller-ma 
Are you suggesting that we update the proxy settings in the docker image of _openhab-cloud_? Let me see if that fixes the issue for me.

**Comment by mueller-ma** [comment] 2019-10-26 12:32
Can you post the current nginx config?
