### ISSUE TITLE
Switching the visibility of charts does not work

### ISSUE THREAD

**Issue by GitSchorsch** [openhab/openhab-android#1094] opened 2018-11-12 21:26 UTC
I have added a chart in my sitemap, which can be switched "on" with different periods and also can be switched off (by setting all visibilities to falsd), to save time when loading the frame. When all visibilities are "false" (so that no chart is visible) and now one of the chart items is set to visible, no chart is beeing displayed. To make the chart visible, it's necessary to reload the page. The same vice versa, when make the chart invisible the area isn't released.
  
Here is the definition of my chart in the sitemap:
```
Frame {
   Switch item=TemperaturChartPeriod label="Temperaturverlauf" mappings=[0="4 Hours", 1="Day", 2="Week", 3="aus"]                
   Chart item=Wassersensor_1_Temperature period=4h refresh=60   visibility=[TemperaturChartPeriod==0]
   Chart item=Wassersensor_1_Temperature period=D  refresh=600  visibility=[TemperaturChartPeriod==1, TemperaturChartPeriod=="Uninitialized"]
   Chart item=Wassersensor_1_Temperature period=W  refresh=6000 visibility=[TemperaturChartPeriod==2]
}
```

Before updating to version 2.4 (from November 6th) everything was fine (btw. same behavior in the current Beta Version 2.4.1). After reloading the page with "swipe down" the visibility of the chart can be toggled, but when leaving and re-entering the page, the behavior is back.

**Comment by mueller-ma** [comment] 2018-11-15 18:55
I tried to reproduce this, but I couldn't:
````
                Switch item=Weather_Chart_Period label="Chart Period" icon="chart" mappings=[0="H", 1="D", 2="W", 3="N"]
                Chart item=Weather_Chart period=h refresh=600000 visibility=[Weather_Chart_Period==0, Weather_Chart_Period=="NULL"]
                Chart item=Weather_Chart period=D refresh=3600000 visibility=[Weather_Chart_Period==1]
                Chart item=Weather_Chart period=W refresh=3600000 visibility=[Weather_Chart_Period==2]
````
There is a ` after your second line. Is this just a copy and paste error?
Does this happen for you both local and remote?

PS: You might want to increase the refresh rate, because it's in milliseconds: https://www.openhab.org/docs/configuration/sitemaps.html#element-type-chart

**Comment by GitSchorsch** [comment] 2018-11-15 20:43
The ` in the second line is a paste error, in the sitemap everthing is fine. Thanks a lot for the hint with the wrong refresh rates. I have seperated the sections in my sitemap with nested Frame and Text elements and the example in the first post was too simple. 
Please try the following:
```
    Frame label="first frame" {
        Text label="text" {
            Frame label="second frame" {
               Switch item=TemperaturChartPeriod label="Temperaturverlauf" mappings=[0="4 Hours", 1="Day", 2="Week", 3="aus"]                
               Chart item=Wassersensor_1_Temperature period=4h refresh=600000  visibility=[TemperaturChartPeriod==0]
               Chart item=Wassersensor_1_Temperature period=D  refresh=3600000 visibility=[TemperaturChartPeriod==1, TemperaturChartPeriod=="Uninitialized"]
               Chart item=Wassersensor_1_Temperature period=W  refresh=3600000 visibility=[TemperaturChartPeriod==2]
            }
        }
    }
```

**Comment by GitSchorsch** [comment] 2018-11-15 20:43
Sorry, I accidentally closed the issue.

**Comment by mueller-ma** [comment] 2018-12-07 20:10
I added some debug logging (https://github.com/mueller-ma/openhab.android/commit/0225b57119996de09a32e885168ee164252ae358) and saw that the widget ids get reassigned when the visibility of widgets changes. In this case the app mixed up widget: In @GitSchorsch's sitemap the charts is sometimes rendered with the values of the item `TemperaturChartPeriod`.

**Comment by maniac103** [comment] 2018-12-07 21:22
@mueller-ma In what way exactly does this reassignment happen? Is the issue server side (server sends items under wrong widget ID) or app side?

**Comment by maniac103** [comment] 2018-12-09 10:12
I wonder whether #1109 will have improved things there?

**Comment by mueller-ma** [comment] 2018-12-18 10:56
I don't see any sitemap update events when the visibility of widgets change.

**Comment by maniac103** [comment] 2018-12-18 12:45
Then this definitely is a server side issue. If widget IDs are dynamically reassigned and no update events are emitted, how are we supposed to find out?

**Comment by DerOetzi** [comment] 2018-12-27 22:52
Same issue here but not only with charts, but although switch and text items. What kind of debugging can I do to help to find this error

**Comment by DerOetzi** [comment] 2018-12-27 22:58
As further information, I tested with BasicUI and everything works as expected. So I'm not sure whether it is a problem which is Server-Side.

**Comment by maniac103** [comment] 2018-12-28 07:51
BasicUI can take shortcuts as it also runs server side. IIRC we had this happening in the past.

**Comment by mueller-ma** [comment] 2019-01-02 19:33
@lolodomo How can I see all sent SSE in logs on the server? I would like to know if the SSE really are sent incorrectly or if the implementation in the app is broken, before I open an issue in ESH.

**Comment by lolodomo** [comment] 2019-01-02 23:02
We could add a TRACE log somewhere in this package to log the content of the sent events.

**Comment by mueller-ma** [comment] 2019-01-08 16:14
Yes, that would help debugging this issue.

**Comment by mueller-ma** [comment] 2019-01-11 18:44
I added logging to the app to see the full sse events. I'm using the temperature site of the demo package for testing:
![basic](https://user-images.githubusercontent.com/22525368/51052965-8b8e7880-15d8-11e9-80f0-dda494f9be7b.JPG)

Switching from Week to Day produces the following log:
````
Got SSE event: {"widgetId":"01000103","label":"Weather_Chart","visibility":false,"state":"NULL","item":{"state":"0","editable":false,"type":"Number","name":"Weather_Chart_Period","label":"Chart Period","tags":[],"groupNames":[]},"sitemapName":"demo","pageId":"0100"}
D/WidgetAdapter: Chart url = chart?items=Weather_Chart_Period&period=W&random=1491059636&dpi=160&theme=white&w=683&h=341
I/WidgetImageView: Refreshing image at http://openhab:8080/chart?items=Weather_Chart_Period&period=W&random=1491059636&dpi=160&theme=white&w=683&h=341
I/WidgetImageView: Refreshing image at http://openhab:8080/chart?items=Weather_Chart_Period&period=W&random=1491059636&dpi=160&theme=white&w=683&h=341
Got SSE event: {"widgetId":"01000100","label":"Chart Period","visibility":true,"item":{"state":"0","editable":false,"type":"Number","name":"Weather_Chart_Period","label":"Chart Period","tags":[],"groupNames":[]},"sitemapName":"demo","pageId":"0100"}
Got SSE event: {"widgetId":"01000101","label":"Weather_Chart","visibility":true,"state":"NULL","item":{"state":"0","editable":false,"type":"Number","name":"Weather_Chart_Period","label":"Chart Period","tags":[],"groupNames":[]},"sitemapName":"demo","pageId":"0100"}
Got SSE event: {"widgetId":"01000102","label":"Weather_Chart","visibility":false,"state":"NULL","item":{"state":"0","editable":false,"type":"Number","name":"Weather_Chart_Period","label":"Chart Period","tags":[],"groupNames":[]},"sitemapName":"demo","pageId":"0100"}
````

The events seem correct: The week chart is hidden, the switch is set to `Day` and the day chart is shown. However the app tries to load the chart for the item `Weather_Chart_Period`, which is wrong.

The widget ids in the rest api and sse events match, so that's not the issue:
![rest-w](https://user-images.githubusercontent.com/22525368/51053103-048dd000-15d9-11e9-984e-ea7ee490608c.JPG)

**Comment by mueller-ma** [comment] 2019-01-13 09:35
> Does the widget list before the switch contain all 4 widgets, and is this still the case when refreshing after the switch?

As you can see in my screenshot of the rest api, it doesn't contain hidden widgets. I guess we need to reload the page (like on SITEMAP_CHANGED events) when we get updates for unknown widget ids.

**Comment by maniac103** [comment] 2019-01-13 10:20
This sounds an inconsistency in the API though, doesn't it?
@lolodomo Since you've been working on SSE stuff: is this (invisible items being not listed in the widget list, but being updated via SSE events instead of sitemap change events being sent out) really intentional? @kaikreuzer Maybe you could comment as well if you get a chance?

**Comment by lolodomo** [comment] 2019-01-13 10:39
I don't remember exactly now but I am sure Basic UI does not reload the full page so you have a solution.
I need to dig a little to have a clear idea.

**Comment by lolodomo** [comment] 2019-01-13 10:44
But you have to consider visibility attribute. The initial REST API provides all widgets.
If I correctly remember, Basic UI hides the widget with visibility=false.

**Comment by maniac103** [comment] 2019-01-15 14:00
Basic UI is delivered as pre-rendered HTML AFAICT.

REST API most definitely doesn't deliver the hidden widgets. With the above mentioned demo sitemap:

```
		Text item=Weather_Temperature valuecolor=[Weather_LastUpdate=="NULL"="lightgray",Weather_LastUpdate>90="lightgray",>25="orange",>15="green",>5="orange",<=5="blue"] {
			Frame {
				Text item=Weather_Temp_Max valuecolor=[>25="orange",>15="green",>5="orange",<=5="blue"]
				Text item=Weather_Temp_Min valuecolor=[>25="orange",>15="green",>5="orange",<=5="blue"]
				Text item=Weather_LastUpdate visibility=[Weather_LastUpdate>30] valuecolor=[Weather_LastUpdate>120="orange", Weather_LastUpdate>300="red"]
			}
			Frame {
				Switch item=Weather_Chart_Period label="Chart Period" icon="chart" mappings=[0="Hour", 1="Day", 2="Week"]
				Chart item=Weather_Chart period=h refresh=600000 visibility=[Weather_Chart_Period==0, Weather_Chart_Period=="NULL"]
				Chart item=Weather_Chart period=D refresh=3600000 visibility=[Weather_Chart_Period==1]
				Chart item=Weather_Chart period=W refresh=3600000 visibility=[Weather_Chart_Period==2]
			}
		}
```

the REST API response (`curl http://localhost:8080/rest/sitemaps/demo/0100 | json_reformat`) becomes

```
{
    "id": "0100",
    "title": "Outside Temperature [- °C]",
    "icon": "temperature",
    "link": "http://localhost:8080/rest/sitemaps/demo/0100",
    "parent": {
        "id": "demo",
        "title": "Main Menu",
        "link": "http://localhost:8080/rest/sitemaps/demo/demo",
        "leaf": true,
        "timeout": false
    },
    "leaf": false,
    "timeout": false,
    "widgets": [
        {
            "widgetId": "010000",
            "type": "Frame",
            "label": "",
            "icon": "frame",
            "mappings": [

            ],
            "widgets": [
                {
                    "widgetId": "01000000",
                    "type": "Text",
                    "label": "Todays Maximum [- °C]",
                    "icon": "temperature",
                    "mappings": [

                    ],
                    "item": {
                        "link": "http://localhost:8080/rest/items/Weather_Temp_Max",
                        "state": "NULL",
                        "stateDescription": {
                            "pattern": "%.1f °C",
                            "readOnly": false,
                            "options": [

                            ]
                        },
                        "editable": false,
                        "type": "Number",
                        "name": "Weather_Temp_Max",
                        "label": "Todays Maximum",
                        "category": "temperature",
                        "tags": [

                        ],
                        "groupNames": [
                            "Weather",
                            "Weather_Chart"
                        ]
                    },
                    "widgets": [

                    ]
                },
                {
                    "widgetId": "01000001",
                    "type": "Text",
                    "label": "Todays Minimum [- °C]",
                    "icon": "temperature",
                    "mappings": [

                    ],
                    "item": {
                        "link": "http://localhost:8080/rest/items/Weather_Temp_Min",
                        "state": "NULL",
                        "stateDescription": {
                            "pattern": "%.1f °C",
                            "readOnly": false,
                            "options": [

                            ]
                        },
                        "editable": false,
                        "type": "Number",
                        "name": "Weather_Temp_Min",
                        "label": "Todays Minimum",
                        "category": "temperature",
                        "tags": [

                        ],
                        "groupNames": [
                            "Weather",
                            "Weather_Chart"
                        ]
                    },
                    "widgets": [

                    ]
                }
            ]
        },
        {
            "widgetId": "010001",
            "type": "Frame",
            "label": "",
            "icon": "frame",
            "mappings": [

            ],
            "widgets": [
                {
                    "widgetId": "01000100",
                    "type": "Switch",
                    "label": "Chart Period",
                    "icon": "chart",
                    "mappings": [
                        {
                            "command": "0",
                            "label": "Hour"
                        },
                        {
                            "command": "1",
                            "label": "Day"
                        },
                        {
                            "command": "2",
                            "label": "Week"
                        }
                    ],
                    "item": {
                        "link": "http://localhost:8080/rest/items/Weather_Chart_Period",
                        "state": "NULL",
                        "editable": false,
                        "type": "Number",
                        "name": "Weather_Chart_Period",
                        "label": "Chart Period",
                        "tags": [

                        ],
                        "groupNames": [

                        ]
                    },
                    "widgets": [

                    ]
                },
                {
                    "widgetId": "01000101",
                    "type": "Chart",
                    "label": "Weather_Chart",
                    "icon": "chart",
                    "mappings": [

                    ],
                    "refresh": 600000,
                    "period": "h",
                    "item": {
                        "members": [

                        ],
                        "link": "http://localhost:8080/rest/items/Weather_Chart",
                        "state": "NULL",
                        "editable": false,
                        "type": "Group",
                        "name": "Weather_Chart",
                        "tags": [

                        ],
                        "groupNames": [

                        ]
                    },
                    "widgets": [

                    ]
                }
            ]
        }
    ]
}
```

As one can see there's only one Chart in the response, not 3 of them, and no visibility flag in there.

We can indeed work/hack around this by reloading the page data when encountering events for unknown widgets as suggested by @mueller-ma as stop-gap measure, but I think this should really be fixed server side by (maybe optionally via query parameter)
- listing hidden widgets in the sitemap API response and
- providing the visibility flag in the sitemap API response

**Comment by maniac103** [comment] 2019-01-15 14:10
(I can prepare a patch for the latter if anyone can tell me how to make the OH Eclipse setup use the local Smarthome sources for building instead the jar pulled from Maven)

**Closed** 2019-01-23 19:10 UTC
Labels: bug
