### ISSUE TITLE
Only the first video show 

### ISSUE THREAD

**Issue by gudszent** [openhab/openhab-android#274] opened 2017-03-21 14:20 UTC
Hi, When I have more than one video in a menu, the android client show only the first one. From normal browser show all of them. Is it a limitation, or bug?

BR, 
O.

**Comment by lolodomo** [comment] 2017-10-20 18:04
I cannot reproduce this issue, I am able to display several videos in the same page.
Here is my sitemap examples with 2 videos (in fact I just updated the demo sitemap):
```
Frame label="Multimedia Widgets" {
Video url="http://www.openhab.org/assets/smarthome.mp4"
Video url="http://techslides.com/demos/sample-videos/small.mp4"
}
```
I think your problem is in fact the issue #417. If I connect to the server in HTTPS, no of these videos are rendered, if I connect to the server in HTTP, the two videos are rendered.
@digitaldan : please close this issue.
@gudszent : if your problem is not exactly what is described in issue 417, please provide an update of the demo sitemap that show the issue.

**Closed** 2018-02-05 20:19 UTC
Labels: awaiting feedback, bug, github issue
