### ISSUE TITLE
Missing images when using my.openhab

### ISSUE THREAD

**Issue by staehler** [openhab/openhab-android#116] opened 2015-06-01 15:09 UTC
When using my.openhab on my habdroid all images disappear.
Pictures say more than words.
Connected to WLAN at home:
![2015-06-01 16 59 44](https://cloud.githubusercontent.com/assets/6258158/7915879/b12a015e-0880-11e5-8db7-896759df5b85.png)
Connected via my.openhab:
![2015-06-01 17 00 32](https://cloud.githubusercontent.com/assets/6258158/7915885/ba054040-0880-11e5-96d2-6af4788ff21b.png)
What is going wrong? Is there a bug?

Regards, Michael
##

**Comment by belovictor** [comment] 2015-06-22 20:36
@staehler, to understand what's happening I need to have a look at your sitemaps content as it is sent to habdroid in both cases. First get http://<your local url:8080>/rest/sitemaps and there you will see the URL of your sitemap in <homepage> section. Then please open this local URL and paste the contents here. After that please open https://my.openhab.org/rest/sitemaps/<the last part of local sitemap url> and paste the contents here.

**Comment by staehler** [comment] 2015-06-23 16:39
Hi Victor,
thanks for looking at it. I'll attach both sitefiles as unformatted text. Hope you can find something. If you need further information, please contact me.
Regards,
Michael

=====================
Sitefile local:
ultrashortSitemap ultrashorthttp://192.168.2.5:8080/rest/sitemaps/ultrashortshortSitemap ultrashorthttp://192.168.2.5:8080/rest/sitemaps/ultrashort/shortfalseshort_0Webviewwebview0http://192.168.2.5:8080/proxy?sitemap=ultrashort.sitemap&widgetId=00&baseUrl=http%3A%2F%2F192.168.2.5%3A8080short_2FrameNetzwerk Alarmeframeshort_2_0_0_0_0_0_0TextUPS Status [on line power]usvStringItemusv_stateOLhttp://192.168.2.5:8080/rest/items/usv_stateshort_2_0_0_0_0_0_0_1TextTestergebnis [Done and passed]usvStringItemusv_testDone and passedhttp://192.168.2.5:8080/rest/items/usv_testshort_3FrameZentralfunktionframeshort_3_0SelectionRolloszenenscene0zu1TV2Sonnenaufgang3Schatten4alle auf10selectNumberItemSzenennummerRolloUninitializedhttp://192.168.2.5:8080/rest/items/SzenennummerRolloshort_3_0_1SwitchAllesallesausOFFausSwitchItemAllesAusUninitializedhttp://192.168.2.5:8080/rest/items/AllesAusshort_3_0_1_2SwitchAlle LichterswitchOFFausSwitchItemAlleLichterUninitializedhttp://192.168.2.5:8080/rest/items/AlleLichtershort_4FrameStatusframeshort_4_0SwitchUrlaubfeiertag-offSwitchItemUrlaubOFFhttp://192.168.2.5:8080/rest/items/Urlaubshort_4_0_1SwitchAnwesendpresent-onSwitchItemAnwesendONhttp://192.168.2.5:8080/rest/items/Anwesendshort_4_0_1_2SwitchVerreistverreist-offSwitchItemVerreistOFFhttp://192.168.2.5:8080/rest/items/Verreistshort_4_0_1_2_3SwitchGästeguest-offSwitchItemGaesteOFFhttp://192.168.2.5:8080/rest/items/Gaesteshort_5FrameHeizungframeshort_5_0SwitchHeizperiodewinter-offSwitchItemIsWinterOFFhttp://192.168.2.5:8080/rest/items/IsWintershort_5_0_1TextWohnzimmervideo0501Wohnzimmervideohttp://192.168.2.5:8080/rest/sitemaps/ultrashort/0501true0501_0SelectionWohnzimmer RTRrtr1Standby2Nacht3KomfortNumberItemBetriebsart_RTR_WohnzimmerUninitializedhttp://192.168.2.5:8080/rest/items/Betriebsart_RTR_Wohnzimmer0501_1TextWohnzimmer Ist [23,4 °C]temperature#ff0000NumberItemIstwertWohnzimmer23.44http://192.168.2.5:8080/rest/items/IstwertWohnzimmer0501_2SetpointBasissollwert [- C]temperature16261NumberItemSollwertWohnzimmerUninitializedhttp://192.168.2.5:8080/rest/items/SollwertWohnzimmer0501_3TextStatus Ventil WZ [geschlossen]heater-off#ff0000SwitchItemStatusHeizenWohnzimmerOFFhttp://192.168.2.5:8080/rest/items/StatusHeizenWohnzimmershort_5_0_1_2TextBadbath0502Badbathhttp://192.168.2.5:8080/rest/sitemaps/ultrashort/0502true0502_0SelectionBad RTRrtr1Standby2Nacht3KomfortNumberItemBetriebsart_RTR_BadUninitializedhttp://192.168.2.5:8080/rest/items/Betriebsart_RTR_Bad0502_1TextBad Ist [22,3 °C]temperature#ffa500NumberItemIstwertBad22.3http://192.168.2.5:8080/rest/items/IstwertBad0502_2SetpointBasissollwert [- C]temperature16261NumberItemSollwertBadUninitializedhttp://192.168.2.5:8080/rest/items/SollwertBad0502_3TextStatus Ventil Bad [undefiniert]heaterSwitchItemStatusHeizenBadUninitializedhttp://192.168.2.5:8080/rest/items/StatusHeizenBad

=====================
Sitefile my.openhab:
ultrashortSitemap ultrashorthttps://my.openhab.org/rest/sitemaps/ultrashortshortSitemap ultrashorthttps://my.openhab.org/rest/sitemaps/ultrashort/shortfalseshort_0Webviewwebview0https://my.openhab.org/proxy?sitemap=ultrashort.sitemap&widgetId=00&baseUrl=https%3A%2F%2Fmy.openhab.orgshort_2FrameNetzwerk Alarmeframeshort_2_0_0_0_0_0_0TextUPS Status [on line power]usvStringItemusv_stateOLhttps://my.openhab.org/rest/items/usv_stateshort_2_0_0_0_0_0_0_1TextTestergebnis [Done and passed]usvStringItemusv_testDone and passedhttps://my.openhab.org/rest/items/usv_testshort_3FrameZentralfunktionframeshort_3_0SelectionRolloszenenscene0zu1TV2Sonnenaufgang3Schatten4alle auf10selectNumberItemSzenennummerRolloUninitializedhttps://my.openhab.org/rest/items/SzenennummerRolloshort_3_0_1SwitchAllesallesausOFFausSwitchItemAllesAusUninitializedhttps://my.openhab.org/rest/items/AllesAusshort_3_0_1_2SwitchAlle LichterswitchOFFausSwitchItemAlleLichterUninitializedhttps://my.openhab.org/rest/items/AlleLichtershort_4FrameStatusframeshort_4_0SwitchUrlaubfeiertag-offSwitchItemUrlaubOFFhttps://my.openhab.org/rest/items/Urlaubshort_4_0_1SwitchAnwesendpresent-onSwitchItemAnwesendONhttps://my.openhab.org/rest/items/Anwesendshort_4_0_1_2SwitchVerreistverreist-offSwitchItemVerreistOFFhttps://my.openhab.org/rest/items/Verreistshort_4_0_1_2_3SwitchGästeguest-offSwitchItemGaesteOFFhttps://my.openhab.org/rest/items/Gaesteshort_5FrameHeizungframeshort_5_0SwitchHeizperiodewinter-offSwitchItemIsWinterOFFhttps://my.openhab.org/rest/items/IsWintershort_5_0_1TextWohnzimmervideo0501Wohnzimmervideohttps://my.openhab.org/rest/sitemaps/ultrashort/0501true0501_0SelectionWohnzimmer RTRrtr1Standby2Nacht3KomfortNumberItemBetriebsart_RTR_WohnzimmerUninitializedhttps://my.openhab.org/rest/items/Betriebsart_RTR_Wohnzimmer0501_1TextWohnzimmer Ist [23,4 °C]temperature#ff0000NumberItemIstwertWohnzimmer23.44https://my.openhab.org/rest/items/IstwertWohnzimmer0501_2SetpointBasissollwert [- C]temperature16261NumberItemSollwertWohnzimmerUninitializedhttps://my.openhab.org/rest/items/SollwertWohnzimmer0501_3TextStatus Ventil WZ [geschlossen]heater-off#ff0000SwitchItemStatusHeizenWohnzimmerOFFhttps://my.openhab.org/rest/items/StatusHeizenWohnzimmershort_5_0_1_2TextBadbath0502Badbathhttps://my.openhab.org/rest/sitemaps/ultrashort/0502true0502_0SelectionBad RTRrtr1Standby2Nacht3KomfortNumberItemBetriebsart_RTR_BadUninitializedhttps://my.openhab.org/rest/items/Betriebsart_RTR_Bad0502_1TextBad Ist [22,3 °C]temperature#ffa500NumberItemIstwertBad22.3https://my.openhab.org/rest/items/IstwertBad0502_2SetpointBasissollwert [10,0 C]temperature16261NumberItemSollwertBad10.0https://my.openhab.org/rest/items/SollwertBad0502_3TextStatus Ventil Bad [undefiniert]heaterSwitchItemStatusHeizenBadUninitializedhttps://my.openhab.org/rest/items/StatusHeizenBad

**Comment by belovictor** [comment] 2015-06-23 21:10
It should have been an XML? :-O

**Comment by staehler** [comment] 2015-06-24 12:27
Hmmm, that the output of my browser. Does the request need further parameter to get xml?

**Comment by cribskip** [comment] 2015-06-26 08:15
1. May this be related to #125 ?
2. @staehler please post inside `´´´` tags for better readability, thanks :)

**Comment by staehler** [comment] 2015-06-26 19:17
Next try ;-) With IE Browser I've got XML formatted output.
sitefile at home:
```
<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<sitemap>

<name>ultrashort</name>

<label>Sitemap ultrashort</label>

<link>http://192.168.2.5:8080/rest/sitemaps/ultrashort</link>


-<homepage>

<id>short</id>

<title>Sitemap ultrashort</title>

<link>http://192.168.2.5:8080/rest/sitemaps/ultrashort/short</link>

<leaf>false</leaf>


-<widget>

<widgetId>short_0</widgetId>

<type>Webview</type>

<label/>

<icon>webview</icon>

<height>0</height>

<url>http://192.168.2.5:8080/proxy?sitemap=ultrashort.sitemap&widgetId=00&baseUrl=http%3A%2F%2F192.168.2.5%3A8080</url>

</widget>


-<widget>

<widgetId>short_2</widgetId>

<type>Frame</type>

<label>Netzwerk Alarme</label>

<icon>frame</icon>


-<widget>

<widgetId>short_2_0_0_0_0_0_0</widgetId>

<type>Text</type>

<label>UPS Status [on line power]</label>

<icon>usv</icon>


-<item>

<type>StringItem</type>

<name>usv_state</name>

<state>OL</state>

<link>http://192.168.2.5:8080/rest/items/usv_state</link>

</item>

</widget>


-<widget>

<widgetId>short_2_0_0_0_0_0_0_1</widgetId>

<type>Text</type>

<label>Testergebnis [Done and passed]</label>

<icon>usv</icon>


-<item>

<type>StringItem</type>

<name>usv_test</name>

<state>Done and passed</state>

<link>http://192.168.2.5:8080/rest/items/usv_test</link>

</item>

</widget>

</widget>


-<widget>

<widgetId>short_3</widgetId>

<type>Frame</type>

<label>Zentralfunktion</label>

<icon>frame</icon>


-<widget>

<widgetId>short_3_0</widgetId>

<type>Selection</type>

<label>Rolloszenen</label>

<icon>scene</icon>


-<mapping>

<command>0</command>

<label>zu</label>

</mapping>


-<mapping>

<command>1</command>

<label>TV</label>

</mapping>


-<mapping>

<command>2</command>

<label>Sonnenaufgang</label>

</mapping>


-<mapping>

<command>3</command>

<label>Schatten</label>

</mapping>


-<mapping>

<command>4</command>

<label>alle auf</label>

</mapping>


-<mapping>

<command>10</command>

<label>select</label>

</mapping>


-<item>

<type>NumberItem</type>

<name>SzenennummerRollo</name>

<state>10</state>

<link>http://192.168.2.5:8080/rest/items/SzenennummerRollo</link>

</item>

</widget>


-<widget>

<widgetId>short_3_0_1</widgetId>

<type>Switch</type>

<label>Alles</label>

<icon>allesaus</icon>


-<mapping>

<command>OFF</command>

<label>aus</label>

</mapping>


-<item>

<type>SwitchItem</type>

<name>AllesAus</name>

<state>Uninitialized</state>

<link>http://192.168.2.5:8080/rest/items/AllesAus</link>

</item>

</widget>


-<widget>

<widgetId>short_3_0_1_2</widgetId>

<type>Switch</type>

<label>Alle Lichter</label>

<icon>switch</icon>


-<mapping>

<command>OFF</command>

<label>aus</label>

</mapping>


-<item>

<type>SwitchItem</type>

<name>AlleLichter</name>

<state>Uninitialized</state>

<link>http://192.168.2.5:8080/rest/items/AlleLichter</link>

</item>

</widget>

</widget>


-<widget>

<widgetId>short_4</widgetId>

<type>Frame</type>

<label>Status</label>

<icon>frame</icon>


-<widget>

<widgetId>short_4_0</widgetId>

<type>Switch</type>

<label>Urlaub</label>

<icon>feiertag-off</icon>


-<item>

<type>SwitchItem</type>

<name>Urlaub</name>

<state>OFF</state>

<link>http://192.168.2.5:8080/rest/items/Urlaub</link>

</item>

</widget>


-<widget>

<widgetId>short_4_0_1</widgetId>

<type>Switch</type>

<label>Anwesend</label>

<icon>present-on</icon>


-<item>

<type>SwitchItem</type>

<name>Anwesend</name>

<state>ON</state>

<link>http://192.168.2.5:8080/rest/items/Anwesend</link>

</item>

</widget>


-<widget>

<widgetId>short_4_0_1_2</widgetId>

<type>Switch</type>

<label>Verreist</label>

<icon>verreist-off</icon>


-<item>

<type>SwitchItem</type>

<name>Verreist</name>

<state>OFF</state>

<link>http://192.168.2.5:8080/rest/items/Verreist</link>

</item>

</widget>


-<widget>

<widgetId>short_4_0_1_2_3</widgetId>

<type>Switch</type>

<label>Gäste</label>

<icon>guest-off</icon>


-<item>

<type>SwitchItem</type>

<name>Gaeste</name>

<state>OFF</state>

<link>http://192.168.2.5:8080/rest/items/Gaeste</link>

</item>

</widget>

</widget>


-<widget>

<widgetId>short_5</widgetId>

<type>Frame</type>

<label>Heizung</label>

<icon>frame</icon>


-<widget>

<widgetId>short_5_0</widgetId>

<type>Switch</type>

<label>Heizperiode</label>

<icon>winter-off</icon>


-<item>

<type>SwitchItem</type>

<name>IsWinter</name>

<state>OFF</state>

<link>http://192.168.2.5:8080/rest/items/IsWinter</link>

</item>

</widget>


-<widget>

<widgetId>short_5_0_1</widgetId>

<type>Text</type>

<label>Wohnzimmer</label>

<icon>video</icon>


-<linkedPage>

<id>0501</id>

<title>Wohnzimmer</title>

<icon>video</icon>

<link>http://192.168.2.5:8080/rest/sitemaps/ultrashort/0501</link>

<leaf>true</leaf>


-<widget>

<widgetId>0501_0</widgetId>

<type>Selection</type>

<label>Wohnzimmer RTR</label>

<icon>rtr</icon>


-<mapping>

<command>1</command>

<label>Standby</label>

</mapping>


-<mapping>

<command>2</command>

<label>Nacht</label>

</mapping>


-<mapping>

<command>3</command>

<label>Komfort</label>

</mapping>


-<item>

<type>NumberItem</type>

<name>Betriebsart_RTR_Wohnzimmer</name>

<state>1</state>

<link>http://192.168.2.5:8080/rest/items/Betriebsart_RTR_Wohnzimmer</link>

</item>

</widget>


-<widget>

<widgetId>0501_1</widgetId>

<type>Text</type>

<label>Wohnzimmer Ist [25,8 °C]</label>

<icon>temperature</icon>

<valuecolor>#ff0000</valuecolor>


-<item>

<type>NumberItem</type>

<name>IstwertWohnzimmer</name>

<state>25.82</state>

<link>http://192.168.2.5:8080/rest/items/IstwertWohnzimmer</link>

</item>

</widget>


-<widget>

<widgetId>0501_2</widgetId>

<type>Setpoint</type>

<label>Basissollwert [22,0 C]</label>

<icon>temperature</icon>

<minValue>16</minValue>

<maxValue>26</maxValue>

<step>1</step>


-<item>

<type>NumberItem</type>

<name>SollwertWohnzimmer</name>

<state>22.0</state>

<link>http://192.168.2.5:8080/rest/items/SollwertWohnzimmer</link>

</item>

</widget>


-<widget>

<widgetId>0501_3</widgetId>

<type>Text</type>

<label>Status Ventil WZ [geschlossen]</label>

<icon>heater-off</icon>

<valuecolor>#ff0000</valuecolor>


-<item>

<type>SwitchItem</type>

<name>StatusHeizenWohnzimmer</name>

<state>OFF</state>

<link>http://192.168.2.5:8080/rest/items/StatusHeizenWohnzimmer</link>

</item>

</widget>

</linkedPage>

</widget>


-<widget>

<widgetId>short_5_0_1_2</widgetId>

<type>Text</type>

<label>Bad</label>

<icon>bath</icon>


-<linkedPage>

<id>0502</id>

<title>Bad</title>

<icon>bath</icon>

<link>http://192.168.2.5:8080/rest/sitemaps/ultrashort/0502</link>

<leaf>true</leaf>


-<widget>

<widgetId>0502_0</widgetId>

<type>Selection</type>

<label>Bad RTR</label>

<icon>rtr</icon>


-<mapping>

<command>1</command>

<label>Standby</label>

</mapping>


-<mapping>

<command>2</command>

<label>Nacht</label>

</mapping>


-<mapping>

<command>3</command>

<label>Komfort</label>

</mapping>


-<item>

<type>NumberItem</type>

<name>Betriebsart_RTR_Bad</name>

<state>1</state>

<link>http://192.168.2.5:8080/rest/items/Betriebsart_RTR_Bad</link>

</item>

</widget>


-<widget>

<widgetId>0502_1</widgetId>

<type>Text</type>

<label>Bad Ist [23,6 °C]</label>

<icon>temperature</icon>

<valuecolor>#ff0000</valuecolor>


-<item>

<type>NumberItem</type>

<name>IstwertBad</name>

<state>23.64</state>

<link>http://192.168.2.5:8080/rest/items/IstwertBad</link>

</item>

</widget>


-<widget>

<widgetId>0502_2</widgetId>

<type>Setpoint</type>

<label>Basissollwert [10,0 C]</label>

<icon>temperature</icon>

<minValue>16</minValue>

<maxValue>26</maxValue>

<step>1</step>


-<item>

<type>NumberItem</type>

<name>SollwertBad</name>

<state>10.0</state>

<link>http://192.168.2.5:8080/rest/items/SollwertBad</link>

</item>

</widget>


-<widget>

<widgetId>0502_3</widgetId>

<type>Text</type>

<label>Status Ventil Bad [geschlossen]</label>

<icon>heater-off</icon>

<valuecolor>#ff0000</valuecolor>


-<item>

<type>SwitchItem</type>

<name>StatusHeizenBad</name>

<state>OFF</state>

<link>http://192.168.2.5:8080/rest/items/StatusHeizenBad</link>

</item>

</widget>

</linkedPage>

</widget>

</widget>

</homepage>

</sitemap>
```

sitefile my.openhab
```
<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<sitemap>

<name>ultrashort</name>

<label>Sitemap ultrashort</label>

<link>https://my.openhab.org/rest/sitemaps/ultrashort</link>


-<homepage>

<id>short</id>

<title>Sitemap ultrashort</title>

<link>https://my.openhab.org/rest/sitemaps/ultrashort/short</link>

<leaf>false</leaf>


-<widget>

<widgetId>short_0</widgetId>

<type>Webview</type>

<label/>

<icon>webview</icon>

<height>0</height>

<url>https://my.openhab.org/proxy?sitemap=ultrashort.sitemap&widgetId=00&baseUrl=https%3A%2F%2Fmy.openhab.org</url>

</widget>


-<widget>

<widgetId>short_2</widgetId>

<type>Frame</type>

<label>Netzwerk Alarme</label>

<icon>frame</icon>


-<widget>

<widgetId>short_2_0_0_0_0_0_0</widgetId>

<type>Text</type>

<label>UPS Status [on line power]</label>

<icon>usv</icon>


-<item>

<type>StringItem</type>

<name>usv_state</name>

<state>OL</state>

<link>https://my.openhab.org/rest/items/usv_state</link>

</item>

</widget>


-<widget>

<widgetId>short_2_0_0_0_0_0_0_1</widgetId>

<type>Text</type>

<label>Testergebnis [Done and passed]</label>

<icon>usv</icon>


-<item>

<type>StringItem</type>

<name>usv_test</name>

<state>Done and passed</state>

<link>https://my.openhab.org/rest/items/usv_test</link>

</item>

</widget>

</widget>


-<widget>

<widgetId>short_3</widgetId>

<type>Frame</type>

<label>Zentralfunktion</label>

<icon>frame</icon>


-<widget>

<widgetId>short_3_0</widgetId>

<type>Selection</type>

<label>Rolloszenen</label>

<icon>scene</icon>


-<mapping>

<command>0</command>

<label>zu</label>

</mapping>


-<mapping>

<command>1</command>

<label>TV</label>

</mapping>


-<mapping>

<command>2</command>

<label>Sonnenaufgang</label>

</mapping>


-<mapping>

<command>3</command>

<label>Schatten</label>

</mapping>


-<mapping>

<command>4</command>

<label>alle auf</label>

</mapping>


-<mapping>

<command>10</command>

<label>select</label>

</mapping>


-<item>

<type>NumberItem</type>

<name>SzenennummerRollo</name>

<state>10</state>

<link>https://my.openhab.org/rest/items/SzenennummerRollo</link>

</item>

</widget>


-<widget>

<widgetId>short_3_0_1</widgetId>

<type>Switch</type>

<label>Alles</label>

<icon>allesaus</icon>


-<mapping>

<command>OFF</command>

<label>aus</label>

</mapping>


-<item>

<type>SwitchItem</type>

<name>AllesAus</name>

<state>Uninitialized</state>

<link>https://my.openhab.org/rest/items/AllesAus</link>

</item>

</widget>


-<widget>

<widgetId>short_3_0_1_2</widgetId>

<type>Switch</type>

<label>Alle Lichter</label>

<icon>switch</icon>


-<mapping>

<command>OFF</command>

<label>aus</label>

</mapping>


-<item>

<type>SwitchItem</type>

<name>AlleLichter</name>

<state>Uninitialized</state>

<link>https://my.openhab.org/rest/items/AlleLichter</link>

</item>

</widget>

</widget>


-<widget>

<widgetId>short_4</widgetId>

<type>Frame</type>

<label>Status</label>

<icon>frame</icon>


-<widget>

<widgetId>short_4_0</widgetId>

<type>Switch</type>

<label>Urlaub</label>

<icon>feiertag-off</icon>


-<item>

<type>SwitchItem</type>

<name>Urlaub</name>

<state>OFF</state>

<link>https://my.openhab.org/rest/items/Urlaub</link>

</item>

</widget>


-<widget>

<widgetId>short_4_0_1</widgetId>

<type>Switch</type>

<label>Anwesend</label>

<icon>present-on</icon>


-<item>

<type>SwitchItem</type>

<name>Anwesend</name>

<state>ON</state>

<link>https://my.openhab.org/rest/items/Anwesend</link>

</item>

</widget>


-<widget>

<widgetId>short_4_0_1_2</widgetId>

<type>Switch</type>

<label>Verreist</label>

<icon>verreist-off</icon>


-<item>

<type>SwitchItem</type>

<name>Verreist</name>

<state>OFF</state>

<link>https://my.openhab.org/rest/items/Verreist</link>

</item>

</widget>


-<widget>

<widgetId>short_4_0_1_2_3</widgetId>

<type>Switch</type>

<label>Gäste</label>

<icon>guest-off</icon>


-<item>

<type>SwitchItem</type>

<name>Gaeste</name>

<state>OFF</state>

<link>https://my.openhab.org/rest/items/Gaeste</link>

</item>

</widget>

</widget>


-<widget>

<widgetId>short_5</widgetId>

<type>Frame</type>

<label>Heizung</label>

<icon>frame</icon>


-<widget>

<widgetId>short_5_0</widgetId>

<type>Switch</type>

<label>Heizperiode</label>

<icon>winter-off</icon>


-<item>

<type>SwitchItem</type>

<name>IsWinter</name>

<state>OFF</state>

<link>https://my.openhab.org/rest/items/IsWinter</link>

</item>

</widget>


-<widget>

<widgetId>short_5_0_1</widgetId>

<type>Text</type>

<label>Wohnzimmer</label>

<icon>video</icon>


-<linkedPage>

<id>0501</id>

<title>Wohnzimmer</title>

<icon>video</icon>

<link>https://my.openhab.org/rest/sitemaps/ultrashort/0501</link>

<leaf>true</leaf>


-<widget>

<widgetId>0501_0</widgetId>

<type>Selection</type>

<label>Wohnzimmer RTR</label>

<icon>rtr</icon>


-<mapping>

<command>1</command>

<label>Standby</label>

</mapping>


-<mapping>

<command>2</command>

<label>Nacht</label>

</mapping>


-<mapping>

<command>3</command>

<label>Komfort</label>

</mapping>


-<item>

<type>NumberItem</type>

<name>Betriebsart_RTR_Wohnzimmer</name>

<state>1</state>

<link>https://my.openhab.org/rest/items/Betriebsart_RTR_Wohnzimmer</link>

</item>

</widget>


-<widget>

<widgetId>0501_1</widgetId>

<type>Text</type>

<label>Wohnzimmer Ist [25,8 °C]</label>

<icon>temperature</icon>

<valuecolor>#ff0000</valuecolor>


-<item>

<type>NumberItem</type>

<name>IstwertWohnzimmer</name>

<state>25.82</state>

<link>https://my.openhab.org/rest/items/IstwertWohnzimmer</link>

</item>

</widget>


-<widget>

<widgetId>0501_2</widgetId>

<type>Setpoint</type>

<label>Basissollwert [22,0 C]</label>

<icon>temperature</icon>

<minValue>16</minValue>

<maxValue>26</maxValue>

<step>1</step>


-<item>

<type>NumberItem</type>

<name>SollwertWohnzimmer</name>

<state>22.0</state>

<link>https://my.openhab.org/rest/items/SollwertWohnzimmer</link>

</item>

</widget>


-<widget>

<widgetId>0501_3</widgetId>

<type>Text</type>

<label>Status Ventil WZ [geschlossen]</label>

<icon>heater-off</icon>

<valuecolor>#ff0000</valuecolor>


-<item>

<type>SwitchItem</type>

<name>StatusHeizenWohnzimmer</name>

<state>OFF</state>

<link>https://my.openhab.org/rest/items/StatusHeizenWohnzimmer</link>

</item>

</widget>

</linkedPage>

</widget>


-<widget>

<widgetId>short_5_0_1_2</widgetId>

<type>Text</type>

<label>Bad</label>

<icon>bath</icon>


-<linkedPage>

<id>0502</id>

<title>Bad</title>

<icon>bath</icon>

<link>https://my.openhab.org/rest/sitemaps/ultrashort/0502</link>

<leaf>true</leaf>


-<widget>

<widgetId>0502_0</widgetId>

<type>Selection</type>

<label>Bad RTR</label>

<icon>rtr</icon>


-<mapping>

<command>1</command>

<label>Standby</label>

</mapping>


-<mapping>

<command>2</command>

<label>Nacht</label>

</mapping>


-<mapping>

<command>3</command>

<label>Komfort</label>

</mapping>


-<item>

<type>NumberItem</type>

<name>Betriebsart_RTR_Bad</name>

<state>1</state>

<link>https://my.openhab.org/rest/items/Betriebsart_RTR_Bad</link>

</item>

</widget>


-<widget>

<widgetId>0502_1</widgetId>

<type>Text</type>

<label>Bad Ist [23,6 °C]</label>

<icon>temperature</icon>

<valuecolor>#ff0000</valuecolor>


-<item>

<type>NumberItem</type>

<name>IstwertBad</name>

<state>23.64</state>

<link>https://my.openhab.org/rest/items/IstwertBad</link>

</item>

</widget>


-<widget>

<widgetId>0502_2</widgetId>

<type>Setpoint</type>

<label>Basissollwert [10,0 C]</label>

<icon>temperature</icon>

<minValue>16</minValue>

<maxValue>26</maxValue>

<step>1</step>


-<item>

<type>NumberItem</type>

<name>SollwertBad</name>

<state>10.0</state>

<link>https://my.openhab.org/rest/items/SollwertBad</link>

</item>

</widget>


-<widget>

<widgetId>0502_3</widgetId>

<type>Text</type>

<label>Status Ventil Bad [geschlossen]</label>

<icon>heater-off</icon>

<valuecolor>#ff0000</valuecolor>


-<item>

<type>SwitchItem</type>

<name>StatusHeizenBad</name>

<state>OFF</state>

<link>https://my.openhab.org/rest/items/StatusHeizenBad</link>

</item>

</widget>

</linkedPage>

</widget>

</widget>

</homepage>

</sitemap>
```

Hope you can work with this output.

Kind regards, Michael

**Comment by belovictor** [comment] 2015-06-27 11:51
Ok, this all looks fine. Can you now check what will happen if you request one of those icons directly? For example with https://my.openhab.org/images/allesaus.png ?

**Comment by staehler** [comment] 2015-06-27 15:20
I can see this image, when I call it in the browser directly. That's 
quite strange for me ...
I've forgotten to say, that only on habdroid this images disappeared. 
When I call the URL on my browser, it's all fine.

Am 27.06.2015 um 13:51 schrieb belovictor:
>
> Ok, this all looks fine. Can you now check what will happen if you 
> request one of those icons directly? For example with 
> https://my.openhab.org/images/allesaus.png ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openhab/openhab.android/issues/116#issuecomment-116019907>.
>

-- 
Viele Grüße,

Michael Pophal

**Comment by belovictor** [comment] 2015-07-05 20:02
This is really strange. Can you get logcat from your Android device when starting the app and loading the page with missing images?

**Comment by adrianmihai83** [comment] 2015-09-09 10:34
Is there a solution to this problem? I have the exact problem, I can see the image if I adress it directly from myopenhab but does not show in the android app.

**Comment by Mr-Swigg** [comment] 2015-12-21 17:58
I had the same issue in the Android app, and solved it by setting the remote URL to https. 

"openHAB Remote URL":
https://my.openhab.org

**Comment by staehler** [comment] 2015-12-29 09:01
Https:// doesn't solve this issue for me, unfortunately.
The Problem still remains :-(

**Comment by shorty707** [comment] 2016-01-23 18:28
same here .... 
just using OH2 Beta in Demo...
no modifications

**Comment by digitaldan** [comment] 2016-05-24 21:20
Can anyone comment if this is still happening?

**Comment by anordvall** [comment] 2016-06-22 21:25
I have had the same problem for months... and now, after reading this thread, I changed from http to https as suggesed above, and it works! Finally I have Icons again! :) Thanks @Mr-Swigg

**Comment by staehler** [comment] 2016-06-23 05:55
Did you run your remote openhab URL just with http? I would expect, that this doesn't work anyway, as it is highly unsecure. My habdroid shows no icons with openHAB remote URL https://my.openhab.org   
 Am 22-Jun-2016 23:25:07 +0200 schrieb notifications@github.com: 

I have had the same problem for months... and now, after reading this thread, I changed from http to https as suggesed above, and it works! Finally I have Icons again! :) Thanks @Mr-Swigg

**Comment by anordvall** [comment] 2016-06-24 12:37
Yes I used http before. It worked just fine, except for the icons. Try changing to http temporary.. or maybe to https://IP:port. Maybe it's some kind of caching problem which disappears when changing the URL.

**Comment by Br3nda** [comment] 2016-07-08 19:59
Did you try "clear images cache" in the android app menu?

**Comment by staehler** [comment] 2016-07-09 10:18
Yes, I did, but the behaviour didn't change. Seems, that I have to life with that :-(

**Comment by Snickermicker** [comment] 2017-01-12 15:53
Seem to have the same issue even when using https.
habdroid (latest from master) throws the following exception for **all** icons:
<pre><code>01-12 16:29:02.092 10210-11043/org.openhab.habdroid W/System.err: java.io.FileNotFoundException: https://myopenhab.org/images/clock.png
01-12 16:29:02.093 10210-11043/org.openhab.habdroid W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
01-12 16:29:02.093 10210-11043/org.openhab.habdroid W/System.err:     at java.net.URLConnection$DefaultContentHandler.getContent(URLConnection.java:1017)
01-12 16:29:02.093 10210-11043/org.openhab.habdroid W/System.err:     at java.net.URLConnection.getContent(URLConnection.java:199)
01-12 16:29:02.093 10210-11043/org.openhab.habdroid W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getContent(DelegatingHttpsURLConnection.java:133)
01-12 16:29:02.094 10210-11043/org.openhab.habdroid W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getContent(HttpsURLConnectionImpl.java)
01-12 16:29:02.094 10210-11043/org.openhab.habdroid W/System.err:     at org.openhab.habdroid.util.MyWebImage.getBitmapFromUrl(MyWebImage.java:107)
01-12 16:29:02.094 10210-11043/org.openhab.habdroid W/System.err:     at org.openhab.habdroid.util.MyWebImage.getBitmap(MyWebImage.java:77)
01-12 16:29:02.094 10210-11043/org.openhab.habdroid W/System.err:     at com.loopj.android.image.SmartImageTask.run(Unknown Source)
01-12 16:29:02.094 10210-11043/org.openhab.habdroid W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-12 16:29:02.094 10210-11043/org.openhab.habdroid W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-12 16:29:02.094 10210-11043/org.openhab.habdroid W/System.err:     at java.lang.Thread.run(Thread.java:818)</code></pre>

The icon is shown OK in android browser when requested directly (after login) `https://myopenhab.org/images/clock.png`

**Comment by Snickermicker** [comment] 2017-01-13 18:09
Guess I found the problem. It seems to be dependending on the password.
By changing
<pre><code> encodedUserPassword = Base64.encodeToString(userPassword.getBytes("UTF-8"), Base64.DEFAULT;</code></pre>
to
<pre><code> encodedUserPassword = Base64.encodeToString(userPassword.getBytes("UTF-8"), Base64.NO_WRAP); </code></pre>

in file mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java (getBitmapFromUrl()) I got all images. I'm going to create a pull request for this.

**Comment by djoope** [comment] 2017-01-26 16:29
I have a similar problem.

http://myopenhab.org works but dont show any icons in my Android app 

http**S**://myopenhab.org just stays at reloading sitemap in my Android app. No content at all. 
I am using a Google Pixel Phone Android 7.1.1

When trying with my Google Nexus 9 tablet outside my home booth Url:s work. 
And show icons when using https://...

Using browser in Google Pixel phone works well with https://home.myopenhab.org/basicui....

Anyone knows about this or are using google Pixel with the app? 
I guess the problem is about my phone?

Thanx in advance

**Comment by lolodomo** [comment] 2017-10-20 18:22
@digitaldan : this issue can be closed as a fix has apparently been merged ?

**Comment by mueller-ma** [comment] 2018-02-05 20:23
Does anyone still have this issue?

**Comment by staehler** [comment] 2018-02-06 14:36
No, this issue ssems to be fixed for me.


Am 5. Februar 2018 9:23:33 PM schrieb mueller-ma <notifications@github.com>:

**Closed** 2018-02-06 15:17 UTC
Labels: awaiting feedback, bug, github issue
