### ISSUE TITLE
App crashes on push notification

### ISSUE THREAD

**Issue by fabrizioromanelli** [openhab/openhab-android#2065] opened 2020-06-19 08:37 UTC
### Actual behaviour
When the openHab app receives a push notification, it crashes and exit immediately.

### Expected behaviour
The notification should be showed on the phone.

### Steps to reproduce
1. Open the app
2. Send a notification from the openHab server

### Can you reproduce the issue in demo mode?
It cannot be reproduced on demo.

#### Client
* Android version: 8.1.0
* Device model: Asus Zenfone Max 3 (ASUS_X008D)
* App version: 2.13.4-beta
* Build flavor: Full
* Device language: English

#### Server
* Server version: 2.5.5-1
* Reverse Proxy: none
* Authentication method: none

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: myhopenhab.org
* openHAB Cloud version: 2.5.5
* Authentication method: user and password

#### App log
<details>
  <summary>Click to expand</summary>

```
Please add the app log if the issue is not a pure UI issue or it cannot be reproduced in demo mode.
Open the app, go to `Settings` => `View log` and insert the log here.
```

</details>

#### openHAB Server log
<details>
  <summary>Click to expand</summary>

```
Not required.
If you have installed openHAB via `apt-get`, the log is located under `/var/log/openhab2/openhab.log`
```

</details>

**Comment by mueller-ma** [comment] 2020-06-19 08:52
This is a duplicate of  #2044.

**Closed by mueller-ma** 2020-06-19 08:52 UTC
Labels: bug
