### ISSUE TITLE
BUG openhab-android version 2.7.11 beta ) The application crashes when I try to change the options available in the scene selection

### ISSUE THREAD

**Issue by friendsmobile** [openhab/openhab-android#1444] opened 2019-07-10 08:42 UTC
# Project Information

* Repository:  https://github.com/openhab/openhab-android
* Project Name:  openhab-android
* My Github Account: https://github.com/friendsmobile
* Download the application:   https://play.google.com/store/apps/details?id=org.openhab.habdroid

# Expected behavior

The option should change and the application should not crash when I try to change the options available in the scene selection.

# Actual behavior

The application crashes when I try to change the options available in the scene selection

#### How to reproduce

* Download the application
*  open the application
* click on Widget Overview
* Try changing the option available in the scene selection
* Note the Error

* Browser/App version: version 2.7.11 beta
* Operating system: 6.0

#### Recording Of The Bug

![20190710_133018](https://user-images.githubusercontent.com/51118734/60953990-106dfc80-a2b3-11e9-9a2d-8ac307a1b7f3.gif)

#### Logcat

<pre><code>D/AndroidRuntime(29301): Shutting down VM

E/AndroidRuntime(29301): FATAL EXCEPTION: main

E/AndroidRuntime(29301): Process: org.openhab.habdroid.beta, PID: 29301

E/AndroidRuntime(29301): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.osmdroid.views.MapView.getContext()' on a null object reference

E/AndroidRuntime(29301): 	at org.osmdroid.views.MapViewRepository.getDefaultMarkerIcon(MapViewRepository.java:74)

E/AndroidRuntime(29301): 	at org.osmdroid.views.overlay.Marker.setDefaultIcon(Marker.java:139)

E/AndroidRuntime(29301): 	at org.osmdroid.views.overlay.Marker.<init>(Marker.java:114)

E/AndroidRuntime(29301): 	at org.osmdroid.views.overlay.Marker.<init>(Marker.java:92)

E/AndroidRuntime(29301): 	at org.openhab.habdroid.ui.MapViewHelperKt.setMarker(MapViewHelper.kt:244)

E/AndroidRuntime(29301): 	at org.openhab.habdroid.ui.MapViewHelperKt.applyPositionAndLabel(MapViewHelper.kt:223)

E/AndroidRuntime(29301): 	at org.openhab.habdroid.ui.MapViewHelper$OsmViewHolder$bind$1.run(MapViewHelper.kt:101)

E/AndroidRuntime(29301): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(29301): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(29301): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(29301): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(29301): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(29301): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(29301): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(29301): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by mueller-ma** [comment] 2019-07-10 14:56
Duplicate of #1443

**Closed by mueller-ma** 2019-07-10 14:56 UTC
Labels: bug
