### ISSUE TITLE
Wear OS Support

### ISSUE THREAD

**Issue by tkarez** [openhab/openhab-android#3064] opened 2022-10-21 15:06 UTC
### Is your feature request related to a problem? Please describe.
Add functionality for WearOS, now that the pixel watch has been released and WearOS 3.5 is out the environment is starting to look somewhat useable. Would like to see an app with tile functionality.

**Comment by rkoshak** [comment] 2022-10-21 15:40
In the mean time, if you have Google Assistant integration enabled, you can install Google Home on the Watch and put a complication. Unfortunately it doesn't appear to support adding an individual control as a complication, but you can launch the Home app and scroll to the control you want.

**Comment by mueller-ma** [comment] 2022-10-21 18:46
Duplicate of #73.

**Closed by mueller-ma** 2022-10-21 18:46 UTC
Labels: enhancement
