### ISSUE TITLE
Font size too small with high-res tablet since version 2.9

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-android#1613] opened 2019-10-17 10:58 UTC
After updating to version 2.9, I discovered that the font size is very small on my old but very high-res tablet (Google Nexus 10).
On my very recent smartphone, the font size is normal.
Is it possible to restore a bigger font for high-res tablet ? Or to add a setting to select the font size ?

**Comment by mueller-ma** [comment] 2019-10-17 11:10
What version did you use before? 2.8?

**Comment by lolodomo** [comment] 2019-10-17 11:25
2.8 was ok, I am sure.? I was then using a 2.8 special version built for me to provide a feedback on switchs with state options and the font was still normal.
The change was certainly introduced during the last weeks before releasing the 2.9.

I have to search how to make a snapshot (I don't remember) to show you the current result.

**Comment by mueller-ma** [comment] 2019-10-17 11:45
> I have to search how to make a snapshot (I don't remember) to show you the current result.

`./gradlew assembleFossBetaDebug`

**Comment by lolodomo** [comment] 2019-10-20 12:11
![image](https://user-images.githubusercontent.com/10186704/67159351-86b6dc00-f343-11e9-970c-6aef507a4cbd.png)

**Comment by maniac103** [comment] 2019-10-20 14:17
This screenshot looks fine to me ... I assume that's the 'before' version?

**Comment by lolodomo** [comment] 2019-10-20 14:39
No the current one.
I see no size difference whatever how is defined my system font size.
Maybe ithe previous version was considering this system setting ?

**Comment by lolodomo** [comment] 2019-10-20 14:45
Is there any chance I can retrieve somewhere the 2.8 apk just to check and show you the difference with 2.9 ?

**Comment by maniac103** [comment] 2019-10-20 15:50
> see no size difference whatever how is defined my system font size.
> Maybe ithe previous version was considering this system setting ?

Let me get this straight: do you mean that you have font scaling enabled in system settings and the problem is just that (parts of) the app don't consider that setting? If that's the case, problem likely is a dp vs. sp mixup in the layout or styles.

**Comment by maniac103** [comment] 2019-10-20 15:52
> Is there any chance I can retrieve somewhere the 2.8 apk just to check and show you the difference with 2.9 ?

Yes: https://github.com/openhab/openhab-android/releases/tag/2.8.0-release

**Comment by lolodomo** [comment] 2019-10-20 16:01
Yes, I setup my system setting to "very large".
Here is the difference with 2.8:
![image](https://user-images.githubusercontent.com/10186704/67162375-a5c56600-f363-11e9-8761-3423f70a7417.png)


Do you see the difference now ? lol

**Comment by lolodomo** [comment] 2019-10-20 16:05
I can confirm that the font size in app depends on the system font size with the version 2.8, while it is now independent from this system setting with the version 2.9.

**Comment by lolodomo** [comment] 2019-10-20 16:08
My tablet is running Android 5.1.1 and this is a pure Google tablet.

**Comment by lolodomo** [comment] 2019-10-25 19:05
Any  thoughts about my problem ?

**Comment by maniac103** [comment] 2019-10-28 13:43
So far I have found out that the issue is not in layouts or styles. It's [the font scaling factor](https://developer.android.com/reference/android/content/res/Configuration?hl=en#fontScale) which isn't populated correctly and stays at 1.0. It also is an Android version specific issue, as the API 22 (5.1) emulator exhibits that issue, while the API 26 (8.0) emulator does not.

**Comment by maniac103** [comment] 2019-10-28 14:00
Looks like this will be fixed via appcompat library update: https://android.googlesource.com/platform/frameworks/support/+/1795e4ebdd262598f3c90b79cd3d75d79a5a2264

**Comment by maniac103** [comment] 2019-10-28 14:08
Found a workaround, see #1643

**Closed** 2019-10-30 06:37 UTC
Labels: bug
