### ISSUE TITLE
AlarmClock item is set to alarm or next event, whichever is soonest

### ISSUE THREAD

**Issue by tarcus69** [openhab/openhab-android#1459] opened 2019-07-26 05:48 UTC
Sorry I filled out the form as requested but the box suggesting I check to see the issue is already present deleted my text when I clicked on "no thanks", wiping out about 15 minutes of careful typing..

Basically using Android 9 on a pixel 3 XL, the AlarmClock item is set to either the alarm time or the time of my next event, e.g. an alarm at 06:30 is reflected in the AlarmClock item, but once that time has passed, it's then set to 19:00 which is the time of my next event. If I turn off my alarm at 06:30 the AlarmClock item is then updated to 19:00 so it's either the time of my next event or the time of the next alarm, whichever is soonest.

Client version is 2.7.0

Log pasted below if this works:
--------- beginning of events
07-26 05:46:34.646 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performPause]
07-26 05:46:34.651 26640 26640 I am_on_activity_result_called: [0,org.openhab.habdroid.ui.MainActivity,ACTIVITY_RESULT]
07-26 05:46:34.651 26640 26640 I am_on_restart_called: [0,org.openhab.habdroid.ui.MainActivity,performRestartActivity]
07-26 05:46:34.660 26640 26640 I am_on_start_called: [0,org.openhab.habdroid.ui.MainActivity,handleStartActivity]
07-26 05:46:34.662 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
07-26 05:46:35.154 26640 26640 I am_on_stop_called: [0,org.openhab.habdroid.ui.PreferencesActivity,LIFECYCLER_STOP_ACTIVITY]
07-26 05:46:35.156 26640 26640 I am_on_destroy_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performDestroy]
07-26 05:47:01.782 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity,performPause]
07-26 05:47:01.820 26640 26640 I am_on_create_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performCreate]
07-26 05:47:01.829 26640 26640 I am_on_start_called: [0,org.openhab.habdroid.ui.PreferencesActivity,handleStartActivity]
07-26 05:47:01.829 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.PreferencesActivity,RESUME_ACTIVITY]
07-26 05:47:02.356 26640 26640 I am_on_stop_called: [0,org.openhab.habdroid.ui.MainActivity,STOP_ACTIVITY_ITEM]
07-26 05:47:23.174 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performPause]
07-26 05:47:23.180 26640 26640 I am_on_activity_result_called: [0,org.openhab.habdroid.ui.MainActivity,ACTIVITY_RESULT]
07-26 05:47:23.180 26640 26640 I am_on_restart_called: [0,org.openhab.habdroid.ui.MainActivity,performRestartActivity]
07-26 05:47:23.183 26640 26640 I am_on_start_called: [0,org.openhab.habdroid.ui.MainActivity,handleStartActivity]
07-26 05:47:23.185 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
07-26 05:47:23.351 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity,performPause]
07-26 05:47:23.355 26640 26640 I am_on_restart_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performRestartActivity]
07-26 05:47:23.355 26640 26640 I am_on_start_called: [0,org.openhab.habdroid.ui.PreferencesActivity,handleStartActivity]
07-26 05:47:23.356 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.PreferencesActivity,RESUME_ACTIVITY]
07-26 05:47:23.851 26640 26640 I am_on_stop_called: [0,org.openhab.habdroid.ui.MainActivity,LIFECYCLER_STOP_ACTIVITY]
07-26 05:47:23.855 26640 26640 I am_on_destroy_called: [0,org.openhab.habdroid.ui.MainActivity,performDestroy]
07-26 05:47:23.860 26640 26640 I am_on_stop_called: [0,org.openhab.habdroid.ui.PreferencesActivity,LIFECYCLER_STOP_ACTIVITY]
07-26 05:47:23.860 26640 26640 I am_on_destroy_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performDestroy]
07-26 05:47:24.408 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performPause]
07-26 05:47:24.415 26640 26640 I am_on_activity_result_called: [0,org.openhab.habdroid.ui.MainActivity,ACTIVITY_RESULT]
07-26 05:47:24.415 26640 26640 I am_on_restart_called: [0,org.openhab.habdroid.ui.MainActivity,performRestartActivity]
07-26 05:47:24.418 26640 26640 I am_on_start_called: [0,org.openhab.habdroid.ui.MainActivity,handleStartActivity]
07-26 05:47:24.419 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
07-26 05:47:24.900 26640 26640 I am_on_stop_called: [0,org.openhab.habdroid.ui.PreferencesActivity,LIFECYCLER_STOP_ACTIVITY]
07-26 05:47:24.901 26640 26640 I am_on_destroy_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performDestroy]
07-26 05:47:25.193 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity,performPause]
07-26 05:47:25.771 26640 26640 I am_on_stop_called: [0,org.openhab.habdroid.ui.MainActivity,LIFECYCLER_STOP_ACTIVITY]
07-26 05:47:25.774 26640 26640 I am_on_destroy_called: [0,org.openhab.habdroid.ui.MainActivity,performDestroy]
07-26 05:47:30.606 26640 26640 I am_on_create_called: [0,org.openhab.habdroid.ui.MainActivity,performCreate]
07-26 05:47:30.612 26640 26640 I am_on_start_called: [0,org.openhab.habdroid.ui.MainActivity,handleStartActivity]
07-26 05:47:30.613 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
07-26 05:49:45.087 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity,performPause]
07-26 05:49:45.115 26640 26640 I am_on_stop_called: [0,org.openhab.habdroid.ui.MainActivity,sleeping]
07-26 06:09:16.415 26640 26640 I am_on_restart_called: [0,org.openhab.habdroid.ui.MainActivity,performRestartActivity]
07-26 06:09:16.446 26640 26640 I am_on_start_called: [0,org.openhab.habdroid.ui.MainActivity,handleStartActivity]
07-26 06:09:16.452 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
07-26 06:09:17.780 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity,performPause]
07-26 06:09:17.813 26640 26640 I am_on_create_called: [0,org.openhab.habdroid.ui.AboutActivity,performCreate]
07-26 06:09:17.816 26640 26640 I am_on_start_called: [0,org.openhab.habdroid.ui.AboutActivity,handleStartActivity]
07-26 06:09:17.817 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.AboutActivity,RESUME_ACTIVITY]
07-26 06:09:18.339 26640 26640 I am_on_stop_called: [0,org.openhab.habdroid.ui.MainActivity,STOP_ACTIVITY_ITEM]
07-26 06:09:20.234 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.AboutActivity,performPause]
07-26 06:09:21.015 26640 26640 I am_on_stop_called: [0,org.openhab.habdroid.ui.AboutActivity,STOP_ACTIVITY_ITEM]
07-26 06:11:55.105 26640 26640 I am_on_restart_called: [0,org.openhab.habdroid.ui.AboutActivity,performRestartActivity]
07-26 06:11:55.105 26640 26640 I am_on_start_called: [0,org.openhab.habdroid.ui.AboutActivity,handleStartActivity]
07-26 06:11:55.105 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.AboutActivity,RESUME_ACTIVITY]
07-26 06:11:56.386 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.AboutActivity,performPause]
07-26 06:11:56.408 26640 26640 I am_on_stop_called: [0,org.openhab.habdroid.ui.AboutActivity,STOP_ACTIVITY_ITEM]
--------- beginning of main
07-26 06:30:01.123 26640 26640 D BackgroundTasksManager: onReceive() with intent android.app.action.NEXT_ALARM_CLOCK_CHANGED
07-26 06:30:01.123 26640 26640 D BackgroundTasksManager: Alarm clock changed
07-26 06:30:01.125 26640 26640 D BackgroundTasksManager: Scheduling work for tag alarmClock
07-26 06:30:01.183 26640 26680 D AbstractConnection: Checking reachability of https://<openhab-local-address>:8443/
07-26 06:30:01.206 26640 26680 D AbstractConnection: Socket connected (attempt  0)
07-26 06:30:01.207 26640 26680 D ConnectionFactory: Connecting to local URL
07-26 06:30:01.212 26640 28807 D ItemUpdateWorker: Trying to get connection
07-26 06:30:01.246 26640 28807 D ItemUpdateWorker: Item 'Pixel3XL_AlarmClock' successfully updated to value 1564164000001
07-26 06:30:01.247 26640 26676 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=d2d7aa86-85c1-4702-a656-17610829659a, tags={ alarmClock, itemUploads, org.openhab.habdroid.background.ItemUpdateWorker } ]
07-26 06:30:12.113 26640 26680 E CloudConnection: Error loading notification settings: java.net.SocketTimeoutException: timeout
07-26 06:30:15.749 26640 26640 D BackgroundTasksManager: onReceive() with intent android.app.action.NEXT_ALARM_CLOCK_CHANGED
07-26 06:30:15.749 26640 26640 D BackgroundTasksManager: Alarm clock changed
07-26 06:30:15.750 26640 26640 D BackgroundTasksManager: Scheduling work for tag alarmClock
07-26 06:30:15.825 26640 28866 D ItemUpdateWorker: Trying to get connection
07-26 06:30:15.886 26640 28866 D ItemUpdateWorker: Item 'Pixel3XL_AlarmClock' successfully updated to value 1564164000001
07-26 06:30:15.889 26640 26676 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=8ee055a6-5237-420a-9743-9a78785b261e, tags={ alarmClock, itemUploads, org.openhab.habdroid.background.ItemUpdateWorker } ]
07-26 06:38:17.669 26640 26640 I am_on_restart_called: [0,org.openhab.habdroid.ui.AboutActivity,performRestartActivity]
07-26 06:38:17.683 26640 26640 I am_on_start_called: [0,org.openhab.habdroid.ui.AboutActivity,handleStartActivity]
07-26 06:38:17.686 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.AboutActivity,RESUME_ACTIVITY]
07-26 06:40:18.196 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.AboutActivity,performPause]
07-26 06:40:18.220 26640 26640 I am_on_stop_called: [0,org.openhab.habdroid.ui.AboutActivity,sleeping]
07-26 06:40:57.340 26640 26640 I am_on_restart_called: [0,org.openhab.habdroid.ui.AboutActivity,performRestartActivity]
07-26 06:40:57.344 26640 26640 I am_on_start_called: [0,org.openhab.habdroid.ui.AboutActivity,handleStartActivity]
07-26 06:40:57.344 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.AboutActivity,RESUME_ACTIVITY]
07-26 06:40:58.299 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.AboutActivity,performPause]
07-26 06:40:58.306 26640 26640 D MainActivity: onActivityResult() requestCode = 1004, resultCode = -1
07-26 06:40:58.306 26640 26640 I am_on_activity_result_called: [0,org.openhab.habdroid.ui.MainActivity,ACTIVITY_RESULT]
07-26 06:40:58.306 26640 26640 I am_on_restart_called: [0,org.openhab.habdroid.ui.MainActivity,performRestartActivity]
07-26 06:40:58.306 26640 26640 D MainActivity: onStart()
07-26 06:40:58.306 26640 26640 D PageConnectionHolderFragment: onStart(), started false
07-26 06:40:58.306 26640 26640 D PageConnectionHolderFragment: Loading data for https://<openhab-local-address>:8443/rest/sitemaps/default/default, long polling false
07-26 06:40:58.309 26640 26640 D WidgetListFragment: onStart() https://<openhab-local-address>:8443/rest/sitemaps/default/default
07-26 06:40:58.309 26640 26640 D PageConnectionHolderFragment: Trigger update for URL https://<openhab-local-address>:8443/rest/sitemaps/default/default, force false
07-26 06:40:58.310 26640 26640 D ContentController: Got update for URL https://<openhab-local-address>:8443/rest/sitemaps/default/default, pending []
07-26 06:40:58.311 26640 26640 D MainActivity: onAvailableConnectionChanged()
07-26 06:40:58.311 26640 26680 D AbstractConnection: Checking reachability of https://<openhab-local-address>:8443/
07-26 06:40:58.313 26640 26640 I am_on_start_called: [0,org.openhab.habdroid.ui.MainActivity,handleStartActivity]
07-26 06:40:58.313 26640 26640 D MainActivity: onResume()
07-26 06:40:58.315 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.MainActivity,RESUME_ACTIVITY]
07-26 06:40:58.361 26640 26680 D AbstractConnection: Socket connected (attempt  0)
07-26 06:40:58.362 26640 26680 D ConnectionFactory: Connecting to local URL
07-26 06:40:58.415 26640 26640 D PageConnectionHolderFragment: Updated page data for URL https://<openhab-local-address>:8443/rest/sitemaps/default/default (32 widgets)
07-26 06:40:58.415 26640 26640 D ContentController: Got update for URL https://<openhab-local-address>:8443/rest/sitemaps/default/default, pending []
07-26 06:40:58.424 26640 26640 I WidgetImageView: Refreshing image at https://<openhab-local-address>:8443/icon/humidity?state=65.1&format=SVG, avoidCache false
07-26 06:40:58.424 26640 26640 I WidgetImageView: Refreshing image at https://<openhab-local-address>:8443/icon/humidity?state=65.1&format=SVG, avoidCache false
07-26 06:40:58.425 26640 26640 I WidgetImageView: Refreshing image at https://<openhab-local-address>:8443/icon/sun?state=5&format=SVG, avoidCache false
07-26 06:40:58.426 26640 26640 I WidgetImageView: Refreshing image at https://<openhab-local-address>:8443/icon/sun?state=5&format=SVG, avoidCache false
07-26 06:40:58.427 26640 26640 I WidgetImageView: Refreshing image at https://<openhab-local-address>:8443/icon/temperature?state=23.571428516932896205&format=SVG, avoidCache false
07-26 06:40:58.427 26640 26640 I WidgetImageView: Refreshing image at https://<openhab-local-address>:8443/icon/temperature?state=23.571428516932896205&format=SVG, avoidCache false
07-26 06:40:58.431 26640 26640 I WidgetImageView: Refreshing image at https://<openhab-local-address>:8443/icon/carbondioxide?state=501%20ppm&format=SVG, avoidCache false
07-26 06:40:58.433 26640 26640 I WidgetImageView: Refreshing image at https://<openhab-local-address>:8443/icon/carbondioxide?state=501%20ppm&format=SVG, avoidCache false
07-26 06:40:58.434 26640 26640 I WidgetImageView: Refreshing image at https://<openhab-local-address>:8443/icon/temperature?state=18.799999237060546875%20%C2%B0C&format=SVG, avoidCache false
07-26 06:40:58.434 26640 26640 I WidgetImageView: Refreshing image at https://<openhab-local-address>:8443/icon/temperature?state=18.799999237060546875%20%C2%B0C&format=SVG, avoidCache false
07-26 06:40:58.778 26640 26640 I am_on_stop_called: [0,org.openhab.habdroid.ui.AboutActivity,LIFECYCLER_STOP_ACTIVITY]
07-26 06:40:58.779 26640 26640 I am_on_destroy_called: [0,org.openhab.habdroid.ui.AboutActivity,performDestroy]
07-26 06:40:59.707 26640 26640 D MainActivity: onCloudConnectionChanged()
07-26 06:40:59.741 26640  2405 D FcmRegistrationService: Register device at openHAB-cloud with URL: addAndroidRegistration?deviceId=1c891ab61239e787&deviceModel=Google+Pixel+3+XL&regId=elQOxT4Gsaw:APA91bG_2CqcLjyUdRqfJ05pXDT-rgOi6LusCoDdT2wzplKFyoqV5WoP80HNOCo7QfQxN9IRHKRmWIS9c9supmdxBCJLzpdWklWuvZm_PqdjgihjzPDJWjeJKrgXFhhctLgxqRD5P9pI
07-26 06:40:59.839 26640 26640 D MainActivity: onOptionsItemSelected()
07-26 06:41:01.101 26640 26640 D MainActivity: onPause()
07-26 06:41:01.101 26640 26640 D WidgetListFragment: onPause() https://<openhab-local-address>:8443/rest/sitemaps/default/default
07-26 06:41:01.101 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.MainActivity,performPause]
07-26 06:41:01.105 26640 26640 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@ac7f2e1
07-26 06:41:01.112 26640 26640 D skia    : --- Failed to create image decoder with message 'unimplemented'
07-26 06:41:01.115 26640 26640 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
07-26 06:41:01.116 26640 26640 I am_on_create_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performCreate]
07-26 06:41:01.123 26640 26640 D PreferencesActivity: Removing notification prefs for < 25
07-26 06:41:01.128 26640 26640 I am_on_start_called: [0,org.openhab.habdroid.ui.PreferencesActivity,handleStartActivity]
07-26 06:41:01.128 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.PreferencesActivity,RESUME_ACTIVITY]
07-26 06:41:01.628 26640 26640 D MainActivity: onSaveInstanceState()
07-26 06:41:01.629 26640 26640 D MainActivity: onStop()
07-26 06:41:01.629 26640 26640 D PageConnectionHolderFragment: onStop()
07-26 06:41:01.629 26640 26640 D PageConnectionHolderFragment: Canceling connection for URL https://<openhab-local-address>:8443/rest/sitemaps/default/default
07-26 06:41:01.629 26640 26640 I am_on_stop_called: [0,org.openhab.habdroid.ui.MainActivity,STOP_ACTIVITY_ITEM]
07-26 06:41:03.706 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.PreferencesActivity,performPause]
07-26 06:41:03.710 26640 26640 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@d9cfdcb
07-26 06:41:03.715 26640 26640 D skia    : --- Failed to create image decoder with message 'unimplemented'
07-26 06:41:03.722 26640 26640 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
07-26 06:41:03.732 26640 26640 I am_on_create_called: [0,org.openhab.habdroid.ui.LogActivity,performCreate]
07-26 06:41:03.733 26640 26640 I am_on_start_called: [0,org.openhab.habdroid.ui.LogActivity,handleStartActivity]
07-26 06:41:03.733 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.LogActivity,RESUME_ACTIVITY]
07-26 06:41:03.748 26640 26640 D LogActivity: onCreateOptionsMenu()
07-26 06:41:03.828 26640 26687 W System  : A resource failed to call response.body().close(). 
07-26 06:41:03.830 26640  2405 D FcmRegistrationService: FCM reg id success
07-26 06:41:04.205 26640 26640 I am_on_stop_called: [0,org.openhab.habdroid.ui.PreferencesActivity,STOP_ACTIVITY_ITEM]
07-26 06:41:19.698 26640 26640 I am_on_paused_called: [0,org.openhab.habdroid.ui.LogActivity,performPause]
07-26 06:41:26.708 26640 26640 I am_on_resume_called: [0,org.openhab.habdroid.ui.LogActivity,RESUME_ACTIVITY]

**Comment by mueller-ma** [comment] 2019-07-26 16:22
My guess is, that your calendar app creates alarms with the alarm api to get a waken up if an event occurs. If so, it's a duplicate of #1341.

**Comment by tarcus69** [comment] 2019-07-26 16:31
Quite likely, I use Tasker and have it reacting to calendar events so it may well have set an alarm action to wake it at the start of the event so I think it's probably safe to assume this is #1341 again. I'll pop over there instead of here.

**Closed** 2019-07-26 16:49 UTC
Labels: bug
