### ISSUE TITLE
Reporting disconnect from charging events immediately

### ISSUE THREAD

**Issue by PMunch** [openhab/openhab-android#2789] opened 2022-01-06 13:45 UTC
### Is your feature request related to a problem? Please describe.
When I start charging my phone I immediately see the state change that my phone is charging in the UI, however when I disconnect it takes a long time before it updates. Since the app updates on different schedules it must be aware that it is no longer connected to power so this event should be possible to send sooner.

### Describe the solution you'd like
Immediate update when phone is unplugged

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by maniac103** [comment] 2022-01-06 14:20
I guess the problem is the Android system just is more lenient in allowing communication for apps while the phone is charging.
Basically whenever the app recognizes an event, it tells the system 'I want to communicate ASAP' to transfer the new event. When the system actually calls back to the app to let it do the transfer is out of the app's control.

**Comment by PMunch** [comment] 2022-01-06 15:31
Well there are settings for how often to send certain events based on charging status. So at least some of it is within control of the app. Besides I remember the HomeAssistant app reported this change instantly, so it's certainly possibly within the Android ecosystem.

**Comment by maniac103** [comment] 2022-01-06 17:28
> So at least some of it is within control of the app.

Sure, for periodic updates the app van generally select the period ... but it's treated as a request/wish and not guaranteed to be followed by the system. The same applies to one time (event based) uploads ... the request is for them to be immediate, but there's no guarantee the system will fulfill it.

That being said, I'll have a look at whether/how we can verify the above actually being the problem. A log of the app after such a delayed item update would be a good start ;-)

**Comment by mueller-ma** [comment] 2022-01-07 07:34
@PMunch Did you turn on "Event listener" in the settings?

**Comment by PMunch** [comment] 2022-01-07 08:40
@mueller-ma, I assume you mean "Event monitor"? In that case yes

**Comment by mueller-ma** [comment] 2022-01-12 15:31
In that case I also think it's the issue @maniac103 describes. I'm not sure what can be done here, the log of the app would be helpful.

Maybe start a service on our own immediatly and try to update the item? WorkManager could still be used for retries.

@PMunch Maybe you can disable some battery saver on your device? https://dontkillmyapp.com/

**Comment by PMunch** [comment] 2022-01-12 15:48
The strange thing is that this worked just fine for HomeAssistant, so it does something different which works better. That was the same phone and I didn't change any battery saver stuff.

**Comment by mueller-ma** [comment] 2022-01-14 10:30
As far as I can see they have several listeners that write updates (e.g. charger connected) to a database. A perdiodic worker is running every 15 minutes and sends all updates since its last run. This worker has a foreground notification, so in our case it might help to mark all work requests as `isImportant`. This will show the notification and mark the work request as expedited: https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt#L581-L583

**Comment by PMunch** [comment] 2022-01-14 13:28
That is another thing which is curious, HomeAssistant manages to do these updates without the persistent notification that OpenHAB requires. A small notification pops up every once in a while saying "Updating sensors" or something similar, but goes away again as soon as it is done transferring.

**Comment by maniac103** [comment] 2022-01-14 14:20
> That is another thing which is curious

That's not curious, just disable 'event monitor' and the notification is gone.
Background: There's two options to do device updates:
- have a service listening for change events (we use this)
- poll for changes at a fixed interval (AFAICT, HA uses this)

The former is more battery efficient and provides instant updates, at the expense of a bit more RAM usage (app needs to be kept in memory) and the persistent notification. The latter doesn't need the notification, but can update only at the specified rate (in HA's case 15 minutes).

@mueller-ma Indeed, we should probably mark everything as important except the updates triggered by the periodic worker.

**Comment by mueller-ma** [comment] 2022-01-15 20:20
@PMunch This persistent notification is on a separate notification channel, so you can safely hide it.

**Closed** 2022-01-19 07:57 UTC
Labels: enhancement
