### ISSUE TITLE
If notifications are deactivated, the app can no longer be used due to a pop-up

### ISSUE THREAD

**Issue by Sprocket02** [openhab/openhab-android#3567] opened 2024-01-14 05:17 UTC
If you want to deactivate the notification for this app, this pop-up constantly appears asking you to reactivate the notification. The pop-up won't go away and I can no longer use the buttons at the bottom.

![Screenshot_20240114-061210](https://github.com/openhab/openhab-android/assets/37394766/2b75d0e1-eb74-4ede-b4c5-dbd8769b716f)

**Comment by mueller-ma** [comment] 2024-01-14 08:09
Duplicate of https://github.com/openhab/openhab-android/issues/3548

Since this is the second issue for this, I reduce the duration of this message: https://github.com/openhab/openhab-android/pull/3568
The app cannot know if there's a rule which will send a notification, so I don't want to hide this message at all.

**Closed** 2024-01-17 18:34 UTC
Labels: bug
