### ISSUE TITLE
Better handling of local/remote url

### ISSUE THREAD

**Issue by mortenn** [openhab/openhab-android#1333] opened 2019-05-02 23:04 UTC
### Is your feature request related to a problem? Please describe.
I have set up my openhab installation to use letsencrypt for both local and remote url.
The local url will result in a certificate error if attempted to be accessed externally.
When this happens, the app will present me with the certificate warning and then give up when I abort the request.

### Describe the solution you'd like
A separate option for local and remote connection to absolutely require a valid cert.
If the validation fails with the option on, it should silently move to the remote url, or vice versa.

**Comment by mueller-ma** [comment] 2019-05-03 13:49
What do you mean with "if attempted to be accessed externally"? From an external wifi or mobile?

**Comment by maniac103** [comment] 2019-05-03 14:09
To me, this seems like overlaying the local/remote logic by a fallback logic (one being the fallback of the other), which I think would have quite some confusion potential.
What's the problem with just accepting that specific certificate for that specific URL?

**Comment by mortenn** [comment] 2019-05-03 17:26
The problem with accepting the certificate is that the url doesn't actually serve up openhab.

**Comment by mortenn** [comment] 2019-05-03 17:27
"if attempted to be accessed externally" - in a context where the remote url should be used.
An option that considers the remote or local url as non-resolving if the certificate is invalid will perfectly give me what I want.

**Comment by mueller-ma** [comment] 2019-05-03 19:13
The way it currently works: If on wifi or vpn, open a tcp socket to the configured local host and port. If that succeeds, try to connect over http(s) to this server.
Instead of opening the tcp socket, we should make an http call to verify if it's an openhab server and try remote connection if not.

**Comment by mortenn** [comment] 2019-05-03 20:49
During that process, it should not show any certificate warnings, imo

**Comment by CrazyIvan359** [comment] 2019-10-19 16:35
Just my 2 cents, but I don't have this problem because I've configured a static route to my openHAB server in my router that points the same url to the internal address of the server. This way I can access it locally using the same url and the certificates all work because the hostname matches.

**Comment by mueller-ma** [comment] 2021-08-29 14:46
Seems like a duplicate of #146 to me.

**Closed by mueller-ma** 2021-08-29 14:46 UTC
Labels: enhancement
