### ISSUE TITLE
Integrate into Android 11 Power Menu

### ISSUE THREAD

**Issue by LinqLover** [openhab/openhab-android#2345] opened 2020-12-27 20:02 UTC
Android 11's new power menu is already used by Google Home to add some smart home shortcuts to this prominent place:

![test](https://www.xda-developers.com/files/2020/06/android-11-home-controls.jpg)

At the moment, the openHAB client appears not to support this new interface. As a workaround, you could try to implement these buttons using Tasker, but why not support this in the openHAB app out of the box?

**Comment by mueller-ma** [comment] 2020-12-27 20:08
> As a workaround, you could try to implement these buttons using Tasker

You can also use quick tiles.

> but why not support this in the openHAB app out of the box?

Because nobody has implemented it yet ;)

I'm closing this as it's a duplicate of #2210.

**Closed by mueller-ma** 2020-12-27 20:08 UTC
Labels: enhancement

**Comment by LinqLover** [comment] 2020-12-27 20:19
Thanks for the hint! If you are referring to [this app](https://play.google.com/store/apps/details?id=com.null73.quicktiles) and its description is up to date, it does not allow you to extend the power menu but only the notification tiles. However, no problem, Tasker looks like a great app and is already on my wishlist :)

**Comment by mueller-ma** [comment] 2020-12-27 21:17
No, I'm talking about the quick tiles feature of openHAB. You can enable them in the app settings => Quick tiles.

**Comment by LinqLover** [comment] 2020-12-27 21:22
Is this a beta feature? I cannot find such an option in v2.15.0, Android 11, not rooted.

**Comment by mueller-ma** [comment] 2020-12-27 21:37
This has been released with 2.14.0, so you should see it. It's on the main settings page of the app and it's called `Tiles for quick settings`. If you cannot see it, please post a screenshot of the end of the main settings page.

**Comment by LinqLover** [comment] 2020-12-27 21:52
Now I found it, I was a bit confused because I am using German labels :)

But neither the tasker plugin nor the tiles can display an item's state at the moment, can they? This would be a useful addition.

**Comment by mueller-ma** [comment] 2020-12-27 22:01
No, they cannot. It would require server-to-mobile connection which isn't easy to implement in a battery saving way.

**Comment by LinqLover** [comment] 2020-12-27 22:16
But how does Google Home solve this? 🤔

**Comment by mueller-ma** [comment] 2020-12-29 10:27
For Tasker, quick tiles and home screen widgets the connection must be permanent. For the new control screen there might be a "start listening to your items" and "stop listening" signal, so the connection must only be kept when the screen is open.

Or they send push messages whenever an "item" changes. When I compare my commercial smart home systems with openHAB, I have a few items (e.g. a few bulbs) vs hundreds of items in openHAB. So openHAB cannot send a push message whenever an item changes.

**Comment by LinqLover** [comment] 2020-12-29 16:52
> For the new control screen there might be a "start listening to your items" and "stop listening" signal, so the connection must only be kept when the screen is open.

I believe there is one. When I open the power menu, I can see a loading message for the Google Home items for a short time. Would be great if this listening mode would be part of the public API.
