### ISSUE TITLE
Habdroid: NFC does not work with current app version 1.6.2

### ISSUE THREAD

**Issue by Schaussi** [openhab/openhab-android#117] opened 2015-06-03 05:39 UTC
With previous versions the NFC feature worked perfectly.
Now when I lay my mobile on an NFC button, it recognizes it - Habdroid opens but only with an empty screen.
##

**Comment by cribskip** [comment] 2015-06-03 09:26
Thanks for reporting.

I just fired up android studio and thought this might be introduced by my change #71 but as testing shows  I can't reproduce.

Environment:
  - HTC One M7 Android 5.0.1
  - TAG freshly written to toggle item (lamp)
  - Habdroid from Playstore (1.7.0.1 I guess)

Test procedure:
  - Selected item by long-press selected toggle
  - on home screen, presented TAG to phone
  - habdroid prints a "connecting to local..." toast and executes the command just fine. ON, OFF, ON, OFF :)

Just read you report again and thought: habdroid should not pop up anymore. there were some changes to disable this behavior.

Please check your installed version and please post your environment (phone, android version, habdroid version).

Thanks
Sascha

**Comment by Schaussi** [comment] 2015-06-03 09:57
Hi Sascha,

thank you for your answer.
Actually, I did not know I can use NFC tags with Habdroid to execute e.g. switch commands directly.
I currently only use NFC to access rooms, e.g. I have an NFC tag in the kitchen which should bring the Openhab room "kitchen" to front.

So to write data to the NFC tag I accessed the room in Habdroid and then chose "Write NFC Tag".
Is maybe this feature not supported any more?

- Habdroid version: the current one from Play Store
- Openhab version: 1.6.2
- Phone: Samsung GT-9195 (Galaxy S4 Mini) with Cyanogenmod 11, Android 4.4.4

**Comment by cribskip** [comment] 2015-06-03 11:05
Hi,

thanks for the further details - now I can confirm: opening sitemap pages by NFC TAG is currently not working.

**May be** related to #71

**Comment by belovictor** [comment] 2015-06-22 20:29
@cribskip , did you do any further investigations to fix sitemap NFC processing?

**Comment by cribskip** [comment] 2015-06-26 08:16
hadn't had time to do so yet. AFAIK only sitemap opening is concerned, TAGs with commands work fine. @Schaussi can you confirm?

**Comment by Schaussi** [comment] 2015-06-26 12:58
Yes I can confirm this.

**Comment by Testato** [comment] 2015-08-04 22:07
Sitemap bug confirmed here too:

OpenHab 1.7.1
Habdroid from store
LG-G3 on Lollipop

**Comment by cribskip** [comment] 2015-08-06 19:33
So I first investigated in #78 and found no possible cause of the problem because my "URL handler" code only triggers if other actions are not triggered.

However, I still can reproduce the error when using my mobile.
I also found no possibility using the emulator to debug the NFC problem.

Next time I'll try to debug with my mobile and ADB :( will be in about 2 weeks :)

**Comment by Schaussi** [comment] 2016-05-24 09:05
I would really appreciate it if you could solve this issue.
It has been about a year now since it appeared.
I wonder if no one else misses this very useful feature?

**Comment by kaikreuzer** [comment] 2016-05-24 11:40
> I wonder if no one else misses this very useful feature?

I do not miss it, since it works for me (at least with the last version on the PlayStore, didn't yet test with 1.8.0)

**Comment by Schaussi** [comment] 2016-05-24 13:35
v1.8.0 came today via Play Store, but unfortunately it does not seem to be solved.
Kai, does the following scenario work for you:
1) Open HabDroid, enter a room
2) Menu -> write NFC tag -> phone writes on NFC hardware button
3) Leave HabDroid
4) Put the phone on the NFC hardware button again
My phone shows an empty HabDroid application.

**Comment by kaikreuzer** [comment] 2016-05-24 22:01
Tested it with HABDroid 1.8.0 from PlayStore and my Nexus 5: NFC works as expected in all cirumstances for me.

**Comment by Schaussi** [comment] 2016-05-25 06:01
I did some further tests today.

HabDroid -> Enter floor, enter room -> long-press item, e.g. "light" -> write NFC tag for "toggle" feature -> read NFC tag -> works, no matter if HabDroid window is currently open or not.

HabDroid -> Enter floor, enter room -> write room NFC tag via top menu option -> Go into main menu and leave HabDroid open -> read NFC tag -> works.
But as soon as I leave HabDroid once (via Back or Home key of the phone), it is the same old behavior again: An empty HabDroid app is shown.
If I then open my HabDroid main menu manually and read the NFC tag, I can see it jumps to the right room for a very short time, e.g. half a second, then goes back to main menu again.

I have been using HabDroid with various Android hardware and OS versions, unfortunately always with the same behavior.

**Comment by Schaussi** [comment] 2016-10-06 16:19
Sorry to bug you again about this, but as this issue keeps getting moved from milestone to milestone for over a year now, I would really appreciate it if you could solve this soon.
Please tell me if I can give you any further information, or any tests etc.

**Comment by JochenHiller** [comment] 2016-10-13 13:58
I can confirm that this bug exists in 1.8.0.3:
* on Nexus 4, Android 6.x
* on Nexus 6P, Android 7.x
* it shows an empty dialog for NFC action ONLY for SwitchItems, ContactItem
It does work as expected for ColorItem, PlayerItem (did not try more)
It will even happen when using DemoMode. So should be easy to reproduce.

![screenshot_2016-10-13-15-50-56](https://cloud.githubusercontent.com/assets/165064/19351850/ac8e8716-915d-11e6-8583-d6b5703590fe.png)

**Comment by kaikreuzer** [comment] 2016-10-13 14:19
Having by now a Honor 8, I actually see the same issue now on Android 6.0.1.
@digitaldan Can you reproduce it on your phone?

**Comment by syphr42** [comment] 2017-02-04 14:48
I reproduced the same issue as @JochenHiller in [#117 (comment)](https://github.com/openhab/openhab.android/issues/117#issuecomment-253520967) just now.

On the off chance it was theme-related, I tested it on all 3 themes (Dark, Light, and Black/AMOLED). The result was the same.

HABDroid 1.8.0.5
Nexus 5X
Android 7.1.1

**Comment by syphr42** [comment] 2017-02-07 04:18
It appears that there are more problems here. The "TOGGLE" option is not working correctly. It actually sends "TOGGLE" to the server in the HTTP POST rather than the correct command.

This code inside OpenHABWidgetListFragment is not executed:
```java
            if (nfcWidget != null && nfcItem != null) {
                // TODO: Perform nfc widget action here
                if (this.nfcCommand.equals("TOGGLE")) {
                    //RollerShutterItem changed to RollerShutter in later builds of OH2
                    if (nfcItem.getType().startsWith("Rollershutter")) {
                        if (nfcItem.getStateAsBoolean())
                            this.openHABWidgetAdapter.sendItemCommand(nfcItem, "UP");
                        else
                            this.openHABWidgetAdapter.sendItemCommand(nfcItem, "DOWN");
                    } else {
                        if (nfcItem.getStateAsBoolean())
                            this.openHABWidgetAdapter.sendItemCommand(nfcItem, "OFF");
                        else
                            this.openHABWidgetAdapter.sendItemCommand(nfcItem, "ON");
                    }
                } else {
                    this.openHABWidgetAdapter.sendItemCommand(nfcItem, this.nfcCommand);
                }
            }
```

Instead, when a tag is read, this code inside OpenHABMainActivity runs:
```java
    public void onNfcTag(String nfcData) {
        Log.d(TAG, "onNfcTag()");
        Uri openHABURI = Uri.parse(nfcData);
        Log.d(TAG, "NFC Scheme = " + openHABURI.getScheme());
        Log.d(TAG, "NFC Host = " + openHABURI.getHost());
        Log.d(TAG, "NFC Path = " + openHABURI.getPath());
        String nfcItem = openHABURI.getQueryParameter("item");
        String nfcCommand = openHABURI.getQueryParameter("command");
        String nfcItemType = openHABURI.getQueryParameter("itemType");
        // If there is no item parameter it means tag contains only sitemap page url
        if (TextUtils.isEmpty(nfcItem)) {
            Log.d(TAG, "This is a sitemap tag without parameters");
            // Form the new sitemap page url
            String newPageUrl = openHABBaseUrl + "rest/sitemaps" + openHABURI.getPath();
            // Check if we have this page in stack?
            mPendingNfcPage = newPageUrl;
        } else {
            Log.d(TAG, "Target item = " + nfcItem);
            sendItemCommand(nfcItem, nfcCommand);
            // if mNfcData is not empty, this means we were launched with NFC touch
            // and thus need to autoexit after an item action
            if (!TextUtils.isEmpty(mNfcData))
                finish();
        }
        mNfcData = "";
    }
```

As you can see in the second version, "TOGGLE" is not translated into commands OH actually understands. Unfortunately, in the code that is executing, all we have are strings (not actual items) so they cannot be queried for type or state.

**Comment by ldet** [comment] 2017-02-27 21:38
If I'm not mistaken Openhab actually understands "TOGGLE".
At least it works for me under OH2 on build 808.
Opening a sitemap page also works for me. But writing an NFC tag for a switch doesn't.
However, when I write it manually with another app, it just works fine:
`openhab://sitemaps/<sitemap>/<sitemap>?item=<item>&command=TOGGLE`

**Comment by Schaussi** [comment] 2017-03-01 15:52
Today I migrated the server from OH1/Windows to OH2/Ubuntu.
For me, it works fine now. It reads the NFC tag and jumps into the right room, like in year 2015 :)
Thank you

**Comment by wdesponts** [comment] 2017-03-09 19:28
@ldet 

Good afternoon Lennart, I'm having a problem with the NFC Switch Trigger in habdroid and would love to try your solution, but alas I think I could use some extra details.  To that end could you explain the following  please:

1) What App (Android) are you using to write the NFC tag?
2) Can you explain/breakdown the uri in your quote better?
    - Do we replace <sitemap> with the name of the sitemap we are using?
    - Do we do the same for <item>
    - Must the item reside in the home screen of the sitemap?
3) Can you confirm that you are using habdroid to trigger the switch?
   - must habdroid be open for this to happen?

I know that this is a lot of questions but if you can help out I'll take the time to create a more complete and NOBS friendly guide to help others until the bug is addressed.

Thanking you in advance for your assistance 

William

**Comment by ldet** [comment] 2017-03-09 22:20
@wdesponts 
For writing i used the NXP tag writer app (others might work):
[https://play.google.com/store/apps/details?id=com.nxp.nfc.tagwriter](url)
With the app u can copy and edit another tag or start completly from scratch.
In both cases Habdroid will be used and opened in background. Depending on your phone its usally necessary to unlock it for the tag to be read.

**The uri builds as follows:**
`openhab://sitemaps/<sitemap>/<page>?item=<item>&command=<command>`
- `<sitemap>` is replaced by your sitemap name
- `<page>` is replaced by your page number or the name of your sitemap if youre on the main page (see below)
- `<item>` your item name
- `<command>` the command you want to send (e.g. `ON`,`OFF`,`TOGGLE`)

How to get your `<page>` number:
- In basciui the URL looks like this:
`https://example.com/basicui/app?w=02&sitemap=home`
=> Page number = 02 (dont cut off any zeros)
If your on the main page of your Sitemap just put in your sitemap name. **or**
- Write a tag in Habdroid with another (non Switch) Item and extract it from the uri as explained above.
You can use the NXP tag writer to read the uri from the tag.

**Examples:**
`openhab://sitemaps/home/02?item=testSwitch&command=TOGGLE`
`openhab://sitemaps/home/home?item=testSwitch&command=OFF`
`openhab://sitemaps/otherSitemap/otherSitemap?item=testSwitch&command=OFF`

**How to get the uri on the tag:**

1.  Start the NXP writer app -> Write tags -> new Dataset -> Link
2.  Change URI type to URI (e.g. ftp, news, telnet, ...)
3.  Enter your uri (copy and paste works)
4. Tap save & write (leave Description empty)
5. make sure everything is disabled execpt "Confirm overwrite" and "Add launch application"
6. Select Habdroid (listed as openHAB)
7. Write your tag ( you will need to confirm again)

Hope this will help you and possibly others to work around this issue. 
Fell free to ask any Questions
Lennart

**Comment by mueller-ma** [comment] 2017-12-22 13:48
Version 1.6.2 is quite old. Can you try it with the latest version?

**Closed** 2018-10-16 16:42 UTC
Labels: bug
