### ISSUE TITLE
Video url crashes app

### ISSUE THREAD

**Issue by cwihne** [openhab/openhab-android#2125] opened 2020-07-31 22:28 UTC
Video url, at least with encoding type HLS, crashes the app instantly. In ~10% of cases the video gets shown nicely. This was working well up to some beta versions ago, also today's 2.13.19-beta crashes.
Example sitemap cutout:
```
sitemap test label="Test" {
	Text label="Köln Bonn Airport" {
		Video url="http://stream-5gw.1000eyes.de/cupertino/cgn2C70DD.stream/playlist.m3u8" encoding="HLS"
	}
}
```

Crash log:
```
--------- beginning of crash
08-01 00:18:44.707 22993 22993 E AndroidRuntime: FATAL EXCEPTION: main
08-01 00:18:44.707 22993 22993 E AndroidRuntime: Process: org.openhab.habdroid.beta, PID: 22993
08-01 00:18:44.707 22993 22993 E AndroidRuntime: java.util.concurrent.CancellationException: Task was cancelled.
08-01 00:18:44.707 22993 22993 E AndroidRuntime: at androidx.media2.player.futures.AbstractResolvableFuture.cancellationExceptionWithCause(AbstractResolvableFuture.java:1193)
08-01 00:18:44.707 22993 22993 E AndroidRuntime: at androidx.media2.player.futures.AbstractResolvableFuture.getDoneValue(AbstractResolvableFuture.java:515)
08-01 00:18:44.707 22993 22993 E AndroidRuntime: at androidx.media2.player.futures.AbstractResolvableFuture.get(AbstractResolvableFuture.java:476)
08-01 00:18:44.707 22993 22993 E AndroidRuntime: at androidx.media2.widget.VideoView$3.run(VideoView.java:666)
08-01 00:18:44.707 22993 22993 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:883)
08-01 00:18:44.707 22993 22993 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:100)
08-01 00:18:44.707 22993 22993 E AndroidRuntime: at android.os.Looper.loop(Looper.java:237)
08-01 00:18:44.707 22993 22993 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8016)
08-01 00:18:44.707 22993 22993 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
08-01 00:18:44.707 22993 22993 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-01 00:18:44.707 22993 22993 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
08-01 00:18:44.732 22993 23040 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-01 00:18:44.732 22993 23040 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
08-01 00:18:44.746 22993 22993 I Process : Sending signal. PID: 22993 SIG: 9
```

Best regards,
Carl.

**Comment by mueller-ma** [comment] 2020-08-02 12:38
This is a duplicate of #1802. I'm going to update this library to the latest alpha version and see if it's getting better.

**Closed by mueller-ma** 2020-08-02 12:38 UTC
Labels: bug

**Comment by mueller-ma** [comment] 2020-08-03 20:34
Can you test 2.13.20-beta?
