### ISSUE TITLE
can't connect to sitemap after update to 1.8.0

### ISSUE THREAD

**Issue by ComJack** [openhab/openhab-android#184] opened 2016-05-23 20:25 UTC
Hi, before few hours i have install the habdroid update to 1.8 on my Nexus tablet.
Now i can't connect to my sitemap, error user or password wrong, but if i open the URL in a browser, it work's. 

the re-install of the app doesn't help.

on my windows phone i can connect to the sitemap with the X:O App.

Openhab 1.8.2
Habdroid 1.8.0
##

**Comment by digitaldan** [comment] 2016-05-23 21:00
Hi @ComJack 
>error user or password wrong

Is this the exact error message?  Does it say this immediately or after a while?

**Comment by jcollie** [comment] 2016-05-24 04:17
After I upgraded, habdroid 1.8.0 doesn't even appear to be trying to connect to my server.  Not a trace of a connection to the server from the phone, and no error messages on the phone either.

**Comment by jcollie** [comment] 2016-05-24 04:20
Firefox works just fine from my phone...

**Comment by kaikreuzer** [comment] 2016-05-24 07:19
@digitaldan I had a similar effect when launching it for the first time on my phone (Nexus 5) - the screen simple stayed empty. After manually accessing the sitemap list and selecting one, it started working.

**Comment by jcollie** [comment] 2016-05-24 14:03
For me the sitemap list was empty as well.  Uninstalling & reinstalling did not help.

**Comment by jcollie** [comment] 2016-05-24 14:12
Hmm.. turning on "Ignore SSL Hostname" made things work.  Not sure why, as I'm using a Let's Encrypt cert and it was working before the upgrade.

**Comment by ComJack** [comment] 2016-05-24 14:35
@digitaldan 

The error msg after a while is "Login error: username or password incorrect, please check username or password incorrect"

i did only the app update and no other changes.

the followin doesn't help.
- reinstall app
- uncheck ignore SSL Hostname etc. 
- remove external URL(my.openhab) and username and password

**Comment by digitaldan** [comment] 2016-05-24 18:36
>The error msg after a while is "Login error: username or password incorrect, please check username or password incorrect"

Hmm, I don't see that error message in the code, the one we use is "Authentication Failed. Please check Username/Password settings" , this is triggered by a 401 response from the server, which would indicate the server is requesting authentication.  I have nexus tablets here I'm using, is there anything else I should know about your setup to reproduce?

**Comment by digitaldan** [comment] 2016-05-24 18:37
>@digitaldan I had a similar effect when launching it for the first time on my phone (Nexus 5) - the screen simple stayed empty. After manually accessing the sitemap list and selecting one, it started working.

hmm, I'll see if i can reproduce.

**Comment by jschanz** [comment] 2016-05-24 21:23
Same problem here. After upgrading to Habdroid 1.8.0 on several phones and tablets, I can't connect to our openHAB instance anymore. This is totally weired, because tcpdump shows some incoming data, but no response from openHAB. Just for information ... This needs tomorrow more debugging.

**Comment by digitaldan** [comment] 2016-05-24 21:55
@jschanz , are you getting any error  messages,  or is it just a blank screen, does the network activity icon spin?  Are you able to get a logcat dump of you android device?  Thanks!

**Comment by jschanz** [comment] 2016-05-24 22:10
After opening the app, I see  the connecting to local url message, but nothing happens. On my S5 this ends in a white screen without sitemap. On my Nexus 10 the network activity icon spins around. 
I'll try to setup this logcat things on my TF101.

**Comment by jschanz** [comment] 2016-05-25 08:29
First: A reboot of the Fritzbox router solved that problem for me. 

But I don't understand the problem itself. Habdroid is connecting with local URL http://192.168.2.167 to openHAB. This seems to work as logcat is showing me, that a connection could be created. A few seconds later, there is a connection request to "openhab.fritz.box / 192.168.2.163". Where does this came from? I had made a downgrade to 1.7.0 and everything was working as expected. Upgrade to 1.8.0 ->No connection.

The hostname of the openHAB-Instance is "openhab.fritz.box", the ip address 192.168.2.167. The former and actually not running openHAB-Instance 1.7.x was located at 192.168.2.163.

So this is totally strange, because every other client in my network could resolve the proper ip for the "new" name. A reboot of the Android devices didn't fixed that, so I don't think the problem is about caching or arp or something else.

For future releases, maybee it is possible to catch the following exception?

```
W/System.err(29516): java.net.ConnectException: failed to connect to openhab.fritz.box/192.168.2.163 (port 80) after 30000ms: isConnected failed: EHOSTUNREACH (No route to host)
```

...
```
D/OpenHABTracker(29516): Checking reachability of http://192.168.2.167/
D/OpenHABTracker(29516): Socket connected
D/OpenHABTracker(29516): Connecting to directly configured URL = http://192.168.2.167/
D/OpenHABMainActivity(29516): onSaveInstanceState
D/OpenHABMainActivity(29516): Saving 0 fragments
D/OpenHABMainActivity(29516): Saving current page = 0
V/WMController(30516): getTask:ComponentInfo{org.openhab.habdroid/org.openhab.habdroid.ui.OpenHABMainActivity}
D/OpenHABMainActivity(29516): onResume()
V/WMController(30516): getTask:ComponentInfo{org.jtb.alogcat/org.jtb.alogcat.LogActivity}
D/dalvikvm(28862): GC_CONCURRENT freed 4650K, 56% free 4782K/10776K, paused 2ms+15ms, total 77ms
D/dalvikvm(30376): GC_FOR_ALLOC freed 1420K, 38% free 11922K/18948K, paused 166ms, total 167ms
E/ActivityThread(29516): Performing pause of activity that is not resumed: {org.openhab.habdroid/org.openhab.habdroid.ui.OpenHABMainActivity}
E/ActivityThread(29516): java.lang.RuntimeException: Performing pause of activity that is not resumed: {org.openhab.habdroid/org.openhab.habdroid.ui.OpenHABMainActivity}
E/ActivityThread(29516): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3027)
E/ActivityThread(29516): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3015)
E/ActivityThread(29516): 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2993)
E/ActivityThread(29516): 	at android.app.ActivityThread.access$1000(ActivityThread.java:135)
E/ActivityThread(29516): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1207)
E/ActivityThread(29516): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ActivityThread(29516): 	at android.os.Looper.loop(Looper.java:136)
E/ActivityThread(29516): 	at android.app.ActivityThread.main(ActivityThread.java:5013)
E/ActivityThread(29516): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/ActivityThread(29516): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/ActivityThread(29516): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/ActivityThread(29516): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/ActivityThread(29516): 	at dalvik.system.NativeStart.main(Native Method)
D/dalvikvm(28862): GC_CONCURRENT freed 570K, 57% free 4639K/10776K, paused 2ms+6ms, total 32ms
D/dalvikvm(28862): GC_CONCURRENT freed 164K, 55% free 4916K/10776K, paused 2ms+4ms, total 32ms
D/dalvikvm(28862): GC_CONCURRENT freed 183K, 52% free 5220K/10776K, paused 4ms+4ms, total 38ms
V/AsyncHttpRH(29516): Request retry no. 1
D/dalvikvm(28862): GC_CONCURRENT freed 84K, 48% free 5647K/10776K, paused 3ms+3ms, total 59ms
D/dalvikvm(28862): WAIT_FOR_CONCURRENT_GC blocked 8ms
D/dalvikvm(28862): GC_CONCURRENT freed 124K, 44% free 6095K/10776K, paused 4ms+14ms, total 54ms
D/dalvikvm(28181): GC_CONCURRENT freed 483K, 10% free 5617K/6192K, paused 7ms+5ms, total 67ms
D/dalvikvm(29516): GC_CONCURRENT freed 477K, 18% free 4954K/6028K, paused 3ms+3ms, total 40ms
D/dalvikvm(28181): GC_CONCURRENT freed 472K, 9% free 5643K/6192K, paused 3ms+4ms, total 35ms
D/dalvikvm(28181): GC_CONCURRENT freed 490K, 10% free 5650K/6216K, paused 2ms+3ms, total 35ms
W/System.err(29516): java.net.ConnectException: failed to connect to openhab.fritz.box/192.168.2.163 (port 80) after 30000ms: isConnected failed: EHOSTUNREACH (No route to host)
W/System.err(29516): 	at libcore.io.IoBridge.isConnected(IoBridge.java:223)
W/System.err(29516): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:161)
W/System.err(29516): 	at libcore.io.IoBridge.connect(IoBridge.java:112)
W/System.err(29516): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
W/System.err(29516): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
W/System.err(29516): 	at crittercism.android.v.connect(Unknown Source)
W/System.err(29516): 	at java.net.Socket.connect(Socket.java:843)
W/System.err(29516): 	at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
W/System.err(29516): 	at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:157)
W/System.err(29516): java.net.ConnectException: failed to connect to openhab.fritz.box/192.168.2.163 (port 80) after 30000ms: isConnected failed: EHOSTUNREACH (No route to host)
W/System.err(29516): 	at libcore.io.IoBridge.isConnected(IoBridge.java:223)
W/System.err(29516): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:161)
W/System.err(29516): 	at libcore.io.IoBridge.connect(IoBridge.java:112)
W/System.err(29516): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
W/System.err(29516): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
W/System.err(29516): 	at crittercism.android.v.connect(Unknown Source)
W/System.err(29516): 	at java.net.Socket.connect(Socket.java:843)
W/System.err(29516): 	at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:117)
W/System.err(29516): 	at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:157)
W/System.err(29516): 	at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
W/System.err(29516): 	at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
W/System.err(29516): 	at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
W/System.err(29516): 	at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
W/System.err(29516): 	at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
W/System.err(29516): 	at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
W/System.err(29516): 	at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
W/System.err(29516): 	at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
W/System.err(29516): 	at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
W/System.err(29516): 	at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
W/System.err(29516): 	at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
W/System.err(29516): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err(29516): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(29516): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(29516): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(29516): 	at java.lang.Thread.run(Thread.java:841)
W/System.err(29516): Caused by: libcore.io.ErrnoException: isConnected failed: EHOSTUNREACH (No route to host)
W/System.err(29516): 	at libcore.io.IoBridge.isConnected(IoBridge.java:208)
W/System.err(29516): 	... 24 more
W/System.err(29516): 	at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
W/System.err(29516): 	at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
W/System.err(29516): 	at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
W/System.err(29516): 	at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
W/System.err(29516): 	at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
W/System.err(29516): 	at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
W/System.err(29516): 	at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
W/System.err(29516): 	at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
W/System.err(29516): 	at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
W/System.err(29516): 	at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
W/System.err(29516): 	at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
W/System.err(29516): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err(29516): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(29516): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(29516): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(29516): 	at java.lang.Thread.run(Thread.java:841)
W/System.err(29516): Caused by: libcore.io.ErrnoException: isConnected failed: EHOSTUNREACH (No route to host)
W/System.err(29516): 	at libcore.io.IoBridge.isConnected(IoBridge.java:208)
W/System.err(29516): 	... 24 more
```

**Comment by digitaldan** [comment] 2016-05-25 14:56
@jschanz thanks for the netcat.  That is very very strange, I'll keep looking at it.

**Comment by casperleenheer** [comment] 2016-05-29 04:45
Same here: I get  HTTP Error: ProxyServlet: /rest/sitemaps

**Comment by digitaldan** [comment] 2016-05-29 13:56
>Same here: I get HTTP Error: ProxyServlet: /rest/sitemaps

@casperleenheer , can you hit "/rest/sitemaps" in your browser or do you get an error? 
If you get an error than this sounds like a problem with your OH instance, you might want to check the forums for help.

**Comment by casperleenheer** [comment] 2016-05-29 16:07
No I get a 404 error. I will search the forums. Thanks.

**Comment by ComJack** [comment] 2016-06-11 06:57
Now i use habdroid 1.8.0.2 and openhab 1.8.3.

i use this URL http://172.28.1.253:8080/openhab.app?sitemap=default
habdroid doesn't work and i get this in the log
172.28.1.116 -  -  [11/Jun/2016:06:52:03 +0000] "GET /openhab.app?sitemap=default/rest/bindings HTTP/1.1" 500 3953 
172.28.1.116 -  -  [11/Jun/2016:06:52:03 +0000] "GET /openhab.app?sitemap=default/rest/sitemaps HTTP/1.1" 500 3953 

if i use the URL in Chrome from the same Client, it works perfekt.

**Comment by jschanz** [comment] 2016-06-11 19:14
@ComJack Your problem is not the same as described here.
Please try the base url like http://172.28.1.253 in habdroid. The entire url will be build by the app.

**Comment by ComJack** [comment] 2016-06-12 07:35
thx, it works.
but before the 1.8.0 update the old url worked also

**Comment by flautze** [comment] 2016-07-08 08:49
Hello,
just to add to this "bug".
I have set up openHAB without username/Password. 
Logging in via Webbrowser seems to be working as intended (even from Android device)
WHen I log in with openHAB via Android device, I get no error message - but the search circle keeps on circling. 
After a while it stops, but the list stays empty and I cannot select any sitemap.

I tried downgrading the openHAB, but that didint resolve the issue, so I am assuming it is an issue of the Android APP.

**Comment by digitaldan** [comment] 2016-07-08 20:39
@flautze what value are you putting in for the "openHAB URL"?

**Comment by flautze** [comment] 2016-07-11 18:39
@digitaldan : openHAB URL is empty, openHAB Remote URL http://[localIP of my openHAB server]

**Comment by digitaldan** [comment] 2016-07-11 19:48
are you including the port in the URL (if it's not 80)?

**Comment by flautze** [comment] 2016-07-12 21:05
Hey, tried without Port, with 8080. Both didn't work.
But today actually it worked with both as well as Port 80. Version   1.8.0.2 still, but I didn't really change anything...

**Comment by LeDumpier** [comment] 2016-08-24 21:44
Hi all,

Similar issue here on Habdroid 1.8.0.2 on my phone. When I try the option 'Select default sitemap' I see two options, demo and _default, neither of which exist in my /etc/openhab2/sitemaps folder.

Under the 'sitemaps' menu I have 'Main Menu' and 'Home'. The 'Main Menu' option goes to the demo sitemap :(

The odd thing is it is working fine on an Acer 7in tablet, also v 1.8.0.2

I've done the uninstall/reinstall thin several times but the phone will not see the sitemap in my sitemaps folder. 

On the phone, when I open the app I see a flash message saying 'Please check that OpenHAB is running or configure OpenHAB URL or remote URL.'

My settings are the same on both devices though. 

It's worked before on my phone but somehow stopped. Any ideas?

**Comment by jurviz** [comment] 2016-12-11 17:00
Hi all, 
i have the same issue on my phone with habdroid 1.8.05 as LeDumpier. Same symptoms as user describes.
Phone is a OnePlus One with Cyanogen OS 13.1.2.
The 3Hou.se app is working normally, both local and remote.
So i tried to track this down to some misconfiguration or so. I did'nt find any hint in my server logs.
I found an app that allows to capture packets on Android without rooting the phone, tPacketCapture, which uses the VPN service to capture network traffic.
But instead of finding the root cause this way, the app is working flawlessly when the capture is activ.
Does anyone have an idea what might be going on?

**Comment by jurviz** [comment] 2016-12-12 18:11
Hi all, i think that was not a defect of the habdroid app, but my server firewall configuration.
I found that the jetty java process was listening on tht IPv6 port 8080 and the access to that port was disallowd by the ufw firewall rules. 
Both apps are now working as expected.

**Comment by LeDumpier** [comment] 2016-12-13 15:13
Hi jurvis,

I tend to agree with you that it's not a Habdroid issue. I was trying to set my system up using my phone as a hotspot and that was causing all kinds of issues, So moving to a router-based WiFi setup I had never seen the issue again.

I hope this helps others out there :)

**Comment by mueller-ma** [comment] 2017-08-24 19:44
@ComJack Do you still have this issue?

**Comment by Djaber19** [comment] 2017-08-29 19:43
Hi, I faced the same problem with the version 1.8.0.8, So any one can helps us to find a solution to be able to remote access the system
thanks for all :)

**Comment by heimia** [comment] 2017-09-23 23:57
Same problem with my openhab2 installation. Using openHAB I get the sitemaps listed. But, if I select one the sitemaps are empty. A look at the https://openhab2.mydomain.com/rest/sitemaps is showing links pointing to https://openhab2/rest/sitemaps/mysitemap. So the "mydomain.com" part is missing.

At the end the question is: How to tell the rest API to use the full domain?

**Comment by heimia** [comment] 2017-09-24 00:11
The error in my case was a miscofiguration of my nginx reverse proxy. As described in http://docs.openhab.org/installation/security.html I had to set the following proxy header:
`proxy_set_header X-Real-IP $remote_addr;`

**Comment by mueller-ma** [comment] 2017-10-09 16:45
@Djaber19 Can you provide a log via logcat?

**Closed** 2018-02-05 20:20 UTC
Labels: awaiting feedback, bug, github issue
